import { getChatGPTUser } from '../../chatgpt-auth';
import { storage } from '../../../db/state';
import {stravaService} from '../../../lib/strava-runtime';
import {readState,writeState,eraseState} from '../../../lib/state-store.mjs';
export const dynamic='force-dynamic';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){const user=await getChatGPTUser();if(!user)return json({error:'Inicia sesión para acceder a tus datos.'},401);try{return json(await readState(storage(),user.userId));}catch(e){console.error('State read failed',e);return json({error:'No se pueden cargar los datos. Reintenta antes de editar.'},503);}}
export async function PUT(request:Request){const user=await getChatGPTUser();if(!user)return json({error:'Inicia sesión para guardar tus datos.'},401);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Origen no permitido.'},403);try{const raw=await request.text();if(raw.length>3000000)return json({error:'El archivo supera el tamaño máximo.'},413);let body:any;try{body=JSON.parse(raw);}catch{return json({error:'Datos inválidos.'},400);}const result=await writeState(storage(),user.userId,body?.state,body?.revision);return result.status===200?json({revision:result.revision}):json({error:result.error,...(result.recalculate?{code:result.code,recalculate:true}:{})},result.status);}catch(e){console.error('State write failed',e);return json({error:'No se ha guardado. Tus cambios siguen en pantalla; vuelve a intentarlo.'},503);}}
export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return json({error:'Inicia sesión.'},401);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Origen no permitido.'},403);try{await stravaService().erase(user.userId);const result=await eraseState(storage(),user.userId);return json({ok:true,revision:result.revision});}catch(e){console.error(e);return json({error:'No se pudieron borrar los datos.'},503);}}
