import test from 'node:test';import assert from 'node:assert/strict';
import {blankProfile,generate,session,validateActivity,seconds,pace,proposal,moveSession,day,daysBetween,addDays,today,metrics,analyze} from '../lib/engine.mjs';
const profile=()=>({...blankProfile(),experience:'regular',weeklyKm:24,longest:10,days:[1,3,6],minutes:{1:60,3:60,6:90},marks:[{date:addDays(today(),-7),distance:5,time:'25:00',effort:'race',context:'competition',measurement:'measured',terrain:'asphalt'}]});
test('pace and time parsing',()=>{assert.equal(seconds('1:02:30'),3750);assert.equal(pace(1800/5),'6:00');assert.ok(Number.isNaN(seconds('4:99')));assert.equal(seconds('32:15'),1935)});
test('blocks sum and availability/time/recovery over varied profiles',()=>{for(const ds of [[1,3,6],[1,2,3],[0,6],[1,2,3,4,5,6,0]])for(const mins of [15,30,60])for(const km of [0,5,10,24,40]){const p={...profile(),weeklyKm:km,days:ds,trainingDays:ds.length,longDay:ds.at(-1),minutes:Object.fromEntries(ds.map(d=>[d,mins]))};const plan=generate(p);for(const s of plan.sessions){assert.ok(ds.includes(day(s.date)));assert.equal(s.seconds,s.blocks.reduce((a,b)=>a+b.seconds,0));if(s.distance!==null)assert.ok(Math.abs(s.distance-s.blocks.reduce((a,b)=>a+b.distance,0))<.011);assert.ok(s.seconds<=p.minutes[day(s.date)]*60,`${s.type} ${s.seconds} > time`);assert.ok(s.blocks.every(b=>b.seconds>=0&&b.distance>=0));}const hard=plan.sessions.filter(s=>s.hard);for(let i=1;i<hard.length;i++)assert.ok(daysBetween(hard[i-1].date,hard[i].date)>=2);}});
test('missing data does not invent paces or measured HR',()=>{const p=blankProfile(),m=metrics(p);assert.equal(m.mark,undefined);const plan=generate(p);assert.ok(plan.sessions.every(s=>s.range===null&&s.hr===null&&s.distance===null));});
test('validation rejects inconsistent activity and laps',()=>{const a={date:today(),distance:5,seconds:1800,rpe:3,laps:[]};assert.deepEqual(validateActivity(a),[]);assert.ok(validateActivity({...a,manualPace:'5:00'}).length);assert.ok(validateActivity({...a,avgHR:180,maxHR:160}).length);assert.ok(validateActivity({...a,laps:[{distance:6,seconds:2000,recoverySeconds:60}]}).length)});
test('fatigue proposal requires decision and leaves plan intact',()=>{const p=profile(),plan=generate(p);const s=plan.sessions[0],a={id:'a',date:s.date,sessionId:s.id,distance:s.distance,seconds:s.seconds,rpe:9,fatigue:8,pain:'none'};const before=JSON.stringify(plan);const v=proposal(a,plan,p);assert.equal(v.status,'pending');assert.equal(JSON.stringify(plan),before);assert.equal(v.after.type,'recovery');assert.ok(v.after.distance<v.before.distance);assert.equal(analyze({...a,rpe:3,fatigue:3},s).action,'mantener');});
test('reorganization rejects unavailable dates',()=>{const p=profile(),plan=generate(p);const s=plan.sessions[0];let d=addDays(today(),1);while(p.days.includes(day(d)))d=addDays(d,1);assert.throws(()=>moveSession(plan,s.id,d,p),/disponible/)});
test('estimated pulse source stays labelled',()=>{const p={...profile(),restHR:60,maxHR:190,hrSource:'estimated'};const plan=generate(p);assert.ok(plan.sessions.every(s=>s.hrSource==='estimated'));});

test("relevant pain prescribes pause",()=>{const p={...profile(),pain:"relevant"};const plan=generate(p);assert.ok(plan.sessions.every(s=>s.type==="rest"&&!s.hard&&s.seconds===0));});

test('race replaces normal session, remains fixed even on unavailable weekday',()=>{for(const goalDay of [1,4,6]){let d=addDays(today(),75);while(day(d)!==goalDay)d=addDays(d,1);const p={...profile(),goal:{type:'race',date:d,distance:10,time:'55:00'}};const plan=generate(p);const event=plan.sessions.filter(s=>s.date===d);assert.equal(event.length,1);assert.equal(event[0].type,'race');assert.equal(event[0].distance,10);assert.ok(plan.sessions.filter(s=>s.date<d&&daysBetween(s.date,d)<=2).every(s=>!s.hard));assert.throws(()=>moveSession(plan,event[0].id,addDays(d,-3),p),/fecha fija/);}});
test('workout catalogue is selected across general, flat and hilly goals, with coherent blocks',()=>{const p=profile(),flat={...p,goal:{type:'race',distance:10,date:addDays(today(),84),intent:'improve',terrain:'asphalt'}},hilly={...flat,goal:{...flat.goal,elevation:100}},plans=[generate(p),generate(flat),generate(hilly)],plan={sessions:plans.flatMap(p=>p.sessions)},types=new Set(plan.sessions.map(s=>s.type));for(const type of ['easy','long','tempo','interval','hills','progressive'])assert.ok(types.has(type),`missing ${type}`);for(const s of plan.sessions){assert.ok(s.reference.includes('5 km'));assert.equal(s.basePace,300);for(const b of s.blocks)if(b.range){assert.ok(b.targetPace>=b.range[0]&&b.targetPace<=b.range[1]);}if(s.type==='hills'){assert.equal(s.distance,null);assert.ok(s.blocks.filter(b=>b.effort===6).every(b=>b.range===null));}}});
test('tempo and interval dose stay stable when only the calendar week changes',()=>{const p=profile(),early=session(p,'tempo',today(),6,0,1),late=session(p,'tempo',today(),6,0,8);assert.deepEqual(late.blocks,early.blocks);assert.equal(session(p,'interval',today(),6,0,1).repetitions.count,4);assert.equal(session(p,'interval',today(),6,0,12).repetitions.count,4);});
