import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {blankProfile,empty,generate,today,addDays,day,daysBetween,session,setTimeZone,timeZone,feasibility,qualityEligibility,validateStateShape,profileErrors,blockKind,pace,speed,recordActivity,seconds} from '../lib/engine.mjs';
import {goalProgress} from '../lib/training.mjs';
const root=fileURLToPath(new URL('..',import.meta.url)),baseRequire=createRequire(import.meta.url),cache={};
// Loads app TSX components and their relative imports for server rendering.
function load(file){if(cache[file])return cache[file].exports;const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,module={exports:{}};cache[file]=module;new Function('require','module','exports',code)(s=>{if(!s.startsWith('.'))return baseRequire(s);const target=path.resolve(path.dirname(file),s);return target.endsWith('.mjs')?baseRequire(target):load(fs.existsSync(target+'.tsx')?target+'.tsx':target+'.ts');},module,module.exports);return module.exports;}
const runner=(over={})=>({...blankProfile(),experience:'regular',weeklyKm:24,longest:10,trainingDays:3,days:[2,4,0],longDay:0,minutes:{2:60,4:60,0:100},marks:[{id:'m',date:addDays(today(),-10),distance:5,time:'25:00',effort:'race',context:'competition',measurement:'measured',terrain:'asphalt'}],goal:{type:'race',intent:'improve',distance:10,date:addDays(today(),70),time:''},...over});

test('calendar dates follow the runner time zone and ignore invalid zones',()=>{const before=timeZone();try{for(const tz of ['Pacific/Kiritimati','Pacific/Pago_Pago','America/Mexico_City','Europe/Madrid']){setTimeZone(tz);assert.equal(today(),new Intl.DateTimeFormat('en-CA',{timeZone:tz}).format(new Date()));}setTimeZone('Not/AZone');assert.equal(timeZone(),'Europe/Madrid');setTimeZone('Pacific/Kiritimati');const far=today();setTimeZone('Pacific/Pago_Pago');/* UTC+14 and UTC−11 are 25 hours apart: dates can differ by two days. */assert.ok(daysBetween(today(),far)>=0&&daysBetween(today(),far)<=2);}finally{setTimeZone(before);}});

test('every session has warm-up, main work, recoveries and cool-down that add up exactly',()=>{const p=runner();for(const type of ['easy','long','tempo','interval','progressive','recovery']){const s=session(p,type,today(),8,0,6);assert.equal(s.blocks[0].kind,'warmup',type);assert.equal(s.blocks.at(-1).kind,'cooldown',type);assert.ok(s.blocks.some(b=>b.kind==='main'),type);assert.ok(Math.abs(s.blocks.reduce((n,b)=>n+b.distance,0)-s.distance)<.011,type);assert.equal(s.blocks.reduce((n,b)=>n+b.seconds,0),s.seconds);for(const b of s.blocks){if(b.distance)assert.equal(Math.round(b.distance*10),b.distance*10,'practical 100 m steps');if(b.targetPace){assert.ok(b.targetPace%5===0);assert.ok(b.targetPace>=b.range[0]&&b.targetPace<=b.range[1]);}}}
 const i=session(p,'interval',today(),8,0,6);assert.ok(i.blocks.filter(b=>b.kind==='recovery').length===i.repetitions.count-1);
 for(const type of ['hills','walk','strength']){const s=session(p,type,today(),0,40,4);assert.equal(s.distance,null);assert.equal(s.blocks[0].kind,'warmup');assert.equal(s.blocks.at(-1).kind,'cooldown');assert.equal(s.blocks.reduce((n,b)=>n+b.seconds,0),s.seconds);}
 assert.equal(pace(360),'6:00');assert.equal(speed(360),10);assert.equal(blockKind('Recuperación · 200 m'),'recovery');assert.equal(blockKind('Vuelta a la calma suave'),'cooldown');});

test('plans respect availability, available minutes, a single race day and the race date',()=>{const dayOptions=[[1,3,6],[2,4,0],[1,2,3,4,5],[6,0],[1,2,3,4,5,6,0]];for(const days of dayOptions)for(const distance of [5,10,21.1,42.2])for(const weeks of [6,12,20]){const date=addDays(today(),weeks*7+3),p=runner({days,trainingDays:Math.min(3,days.length),longDay:days.at(-1),minutes:Object.fromEntries(days.map(d=>[d,d===days.at(-1)?120:50])),goal:{type:'race',distance,date,time:''},weeklyKm:distance>20?35:20});const plan=generate(p);
 const race=plan.sessions.filter(s=>s.type==='race');assert.equal(race.length,1);assert.equal(race[0].date,date);assert.equal(race[0].distance,distance);assert.match(race[0].blocks[0].label,/^Día de la carrera · /);
 assert.ok(plan.sessions.every(s=>s.date<=date&&s.date>=today()),'no session after the race or in the past');assert.equal(new Set(plan.sessions.map(s=>s.date)).size,plan.sessions.length,'one session per day');assert.equal(new Set(plan.sessions.map(s=>s.id)).size,plan.sessions.length);
 for(const s of plan.sessions.filter(s=>s.type!=='race')){assert.ok(days.includes(day(s.date)),`${s.type} on unavailable day`);assert.ok(s.seconds<=p.minutes[day(s.date)]*60);}
 assert.ok(plan.sessions.filter(s=>s.date<date&&daysBetween(s.date,date)<=2).every(s=>!s.hard),'no hard work in the 48 h before racing');
 const taper=plan.sessions.filter(s=>s.phase?.key==='taper'&&s.distance);if(taper.length&&weeks>=12){const peak=Math.max(...plan.sessions.filter(s=>s.distance&&s.type!=='race'&&s.phase?.key!=='taper').map(s=>s.distance));assert.ok(taper.every(s=>s.distance<=peak));}}});

test('ambitious goals are flagged with concrete alternatives instead of promises',()=>{const p=runner({experience:'beginner',weeklyKm:6,longest:4,marks:[],goal:{type:'race',distance:42.2,date:addDays(today(),42),time:'3:30:00'}});const v=feasibility(p);assert.equal(v.cautious,true);assert.ok(v.alternatives.some(a=>a.kind==='date'&&a.goal.date>p.goal.date));assert.ok(v.alternatives.some(a=>a.kind==='distance'&&a.goal.distance===10));
 const fast=runner({goal:{type:'race',distance:10,date:addDays(today(),84),time:'40:00'}}),f=feasibility(fast);assert.equal(f.cautious,true);const t=f.alternatives.find(a=>a.kind==='time');assert.ok(seconds(t.goal.time)>seconds('50:00'));assert.ok(f.alternatives.some(a=>a.kind==='finish'&&a.goal.time===''));
 const later=feasibility({...p,goal:v.alternatives.find(a=>a.kind==='date').goal});assert.ok(!later.notes.some(n=>/semanas/.test(n)&&/dispones de \d semanas/.test(n)&&/42\.2|42,2/.test(n)&&later.weeks<24));});

test('the plan explains which workouts are not suitable yet',()=>{const beginner=runner({experience:'beginner',weeklyKm:6,marks:[]}),plan=generate(beginner),rows=qualityEligibility(beginner,plan),tempo=rows.find(r=>r.type==='tempo');assert.equal(tempo.included,false);assert.match(tempo.reason,/12 km/);assert.ok(plan.sessions.every(s=>!['tempo','interval','hills','progressive'].includes(s.type)));
 const regular=runner(),rp=generate(regular),r2=qualityEligibility(regular,rp);for(const t of ['tempo','interval','long','easy'])assert.ok(r2.find(r=>r.type===t).included,t);
 const sore=runner({pain:'mild'}),r3=qualityEligibility(sore,generate(sore));assert.match(r3.find(r=>r.type==='interval').reason,/molestias/);});

test('server-side shape checks reject duplicated records and links',()=>{const p=runner(),plan=generate(p),s=plan.sessions[0],a={id:'a',date:today(),distance:5,seconds:1800,sessionId:s.id};const ok={...empty(),profile:{...p,timezone:'Europe/Madrid'},plan,activities:[a]};assert.deepEqual(validateStateShape(ok),[]);assert.ok(validateStateShape({...ok,activities:[a,{...a}]}).some(e=>/duplicados/.test(e)));assert.ok(validateStateShape({...ok,activities:[a,{...a,id:'b'}]}).some(e=>/más de una carrera/.test(e)));assert.ok(validateStateShape({...ok,plan:{...plan,sessions:[s,s]}}).some(e=>/duplicados/.test(e)));assert.ok(validateStateShape({...ok,profile:{...p,timezone:'Mars/Base'}}).length);assert.ok(validateStateShape({profile:null}).length);assert.ok(validateStateShape(null).length);});

test('profile validation and goal progress distinguish completed, changed and extra runs',()=>{assert.deepEqual(profileErrors(runner({goal:{type:'race',distance:10,date:'',time:''}})),[]);assert.equal(generate(runner({goal:{type:'race',distance:10,date:'',time:''}})).sessions.some(s=>s.type==='race'),false);assert.deepEqual(profileErrors(runner()),[]);assert.ok(profileErrors(runner({easyPace:'99:99'})).length);
 // A historical plan must use a performance already available at its start, not a future mark.
 const p=runner({marks:[{id:'m',date:addDays(today(),-20),distance:5,time:'25:00',effort:'race',context:'competition',measurement:'measured',terrain:'asphalt'}]}),start=addDays(today(),-14),plan=generate(p,start),past=plan.sessions.filter(s=>s.date<today()&&s.distance&&s.type!=='race');assert.ok(past.length>=3);let state={...empty(),profile:p,plan};
 state=recordActivity(state,{id:'x1',date:past[0].date,distance:past[0].distance,seconds:past[0].seconds,rpe:past[0].rpe,fatigue:3,pain:'none',type:past[0].type,laps:[]}).state;
 state=recordActivity(state,{id:'x2',linkMode:'manual',sessionId:past[1].id,date:past[1].date,distance:round1(past[1].distance*.5),seconds:Math.round(past[1].seconds*.5),rpe:3,fatigue:3,pain:'none',type:past[1].type,laps:[]}).state;
 const freeDay=[...Array(14)].map((_,i)=>addDays(start,i)).find(d=>d<today()&&!plan.sessions.some(s=>s.date===d));state=recordActivity(state,{id:'x3',linkMode:'none',date:freeDay,distance:3,seconds:1200,rpe:3,fatigue:3,pain:'none',type:'easy',laps:[]}).state;
 const g=goalProgress(state);assert.equal(g.completed,1);assert.equal(g.changed,1);assert.equal(g.extra,1);assert.equal(g.missed,past.length-2+plan.sessions.filter(s=>s.date<today()&&!s.distance&&s.type!=='rest').length);assert.ok(g.week>=3);assert.ok(g.race);assert.equal(g.actualKm,Math.round((past[0].distance+round1(past[1].distance*.5)+3)*100)/100);});
const round1=n=>Math.round(n*10)/10;

test('onboarding and Strava connection render real states, never a fake connection',()=>{const strava=load(path.join(root,'app/strava-panel.tsx')),Onboarding=load(path.join(root,'app/onboarding.tsx')).default;
 const pending={configured:false,retentionConfigured:false,state:'disconnected',checklist:[{id:'app',label:'Aplicación registrada',done:false},{id:'key',label:'Clave',done:true}]};
 let html=renderToStaticMarkup(React.createElement(strava.StravaConnectCard,{data:pending,busy:false,settings:strava.defaultStravaSettings,setSettings:()=>{},onConnect:()=>{},onSkip:()=>{}}));assert.match(html,/todavía no está disponible/);assert.match(html,/Pendiente/);assert.match(html,/<button[^>]*disabled=""[^>]*aria-label="Connect with Strava"/);assert.match(html,/Continuar sin Strava/);assert.match(html,/activity:read_all/);assert.match(html,/Prohibido analizar \(5\.4\)/);assert.match(html,/connect-with-strava\.svg/);
 html=renderToStaticMarkup(React.createElement(strava.StravaConnectCard,{data:{...pending,configured:true,retentionConfigured:true},busy:false,settings:strava.defaultStravaSettings,setSettings:()=>{},onConnect:()=>{}}));assert.doesNotMatch(html,/disabled=""[^>]*aria-label="Connect with Strava"/);assert.doesNotMatch(html,/todavía no está disponible/);
 html=renderToStaticMarkup(React.createElement(Onboarding,{account:{name:'Ana Pérez',email:'ana@example.invalid'},state:empty(),save:async()=>true,busy:false,strava:pending,refreshStrava:async()=>{},onFullForm:()=>{},onDemo:()=>{}}));assert.match(html,/PASO 1 DE 7/);assert.match(html,/ana@example\.invalid/);assert.match(html,/Usar el formulario completo/);assert.doesNotMatch(html,/NaN|undefined/);});
