import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {StravaService} from '../lib/strava-service.mjs';import {seal,open,randomSecret,normalizeRun,allowedRun,rotateTokens} from '../lib/strava-core.mjs';
function d1(){
 const db=new DatabaseSync(':memory:');
 db.exec(readFileSync(new URL('../drizzle/0001_luxuriant_jamie_braddock.sql',import.meta.url),'utf8'));
 db.exec(readFileSync(new URL('../drizzle/0002_abnormal_skreet.sql',import.meta.url),'utf8'));
 return {
  prepare(sql){return {bind(...args){return {
   async first(){return db.prepare(sql).get(...args)||null;},
   async all(){return {results:db.prepare(sql).all(...args)};},
   async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}
  };}};},
  async batch(items){db.exec('BEGIN');try{const result=[];for(const item of items)result.push(await item.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}},raw:db
 };
}
const config=()=>({STRAVA_TOKEN_KEY:randomSecret(),STRAVA_CLIENT_ID:'123',STRAVA_CLIENT_SECRET:'test-secret',STRAVA_REDIRECT_URI:'https://example.test/api/strava/callback',STRAVA_RETENTION_JOB_ENABLED:'true',STRAVA_WEBHOOK_SUBSCRIPTION_ID:'42'});
const run={id:100,name:'Carrera real de prueba',athlete:{id:1},sport_type:'Run',start_date:'2026-09-29T22:30:00Z',start_date_local:'2026-09-30T00:30:00Z',timezone:'(GMT+02:00) Europe/Madrid',distance:1234.567,moving_time:444,elapsed_time:470,total_elevation_gain:20.5,laps:[{distance:1000,moving_time:360}]};
function provider(){let deleted=false,changed=run,calls=0;return {setRun:r=>changed=r,remove:()=>deleted=true,get calls(){return calls;},async fetch(url,opts={}){calls++;if(url.includes('/oauth/token'))return Response.json({access_token:'renewed-access',refresh_token:'rotated-refresh',expires_at:Math.floor(Date.now()/1000)+21600,athlete:{id:1},scope:'read activity:read'});if(url.includes('/oauth/revoke')||url.includes('/oauth/deauthorize'))return new Response(null,{status:200});const token=opts.headers?.Authorization;if(!['Bearer user-one-token','Bearer renewed-access','Bearer user-two-token'].includes(token))return new Response(null,{status:401});const athlete=token==='Bearer user-two-token'?2:1;if(url.includes('/athlete/activities'))return Response.json(deleted?[]:[{...changed,athlete:{id:athlete}}]);if(url.endsWith('/athlete'))return Response.json({id:athlete});if(url.includes('/activities/'))return deleted?new Response(null,{status:404}):Response.json({...changed,athlete:{id:athlete}});throw Error('unexpected_provider_call');}};}
test('AES-GCM encryption is bound to the user and never plaintext',async()=>{const key=randomSecret(),cipher=await seal({accessToken:'secret-access',refreshToken:'secret-refresh'},key,'u1');assert(!cipher.includes('secret'));assert.equal((await open(cipher,key,'u1')).refreshToken,'secret-refresh');await assert.rejects(open(cipher,key,'u2'));});
test('local date, metric precision, absent HR, units, laps and run filters',()=>{const a=normalizeRun(run);assert.equal(a.date,'2026-09-30');assert.equal(a.distance,1.234567);assert.equal(a.avgHR,null);assert.equal(a.maxHR,null);assert.equal(a.laps[0].paceSeconds,360);assert.equal(normalizeRun({...run,distance:2000,moving_time:720}).speedKmh,10);assert.equal(normalizeRun({...run,distance:2000,moving_time:720}).paceSeconds,360);for(const sport of ['Walk','Hike','Ride','Workout'])assert.equal(allowedRun({...run,sport_type:sport}),false);assert(!allowedRun({...run,sport_type:'TrailRun'},{includeTrail:false}));assert(!allowedRun({...run,sport_type:'VirtualRun'},{includeTreadmill:false}));assert(!allowedRun({...run,trainer:true},{includeTreadmill:false}));});
test('two users, deduplication, updates, deletions preserve only personal notes',async()=>{const db=d1(),cfg=config(),p=provider(),s=new StravaService(db,cfg,p.fetch);await s.ownToken('u1','user-one-token',{});await s.drain(10);await s.ownToken('u2','user-two-token',{});await s.drain(10);let a=await s.status('u1'),b=await s.status('u2');assert.equal(a.activities.length,1);assert.equal(b.activities.length,1);assert.notEqual(a.activities[0].id,b.activities[0].id);assert.equal(a.account,'Atleta 1');assert.equal(b.account,'Atleta 2');assert(!JSON.stringify(a).includes('user-one-token'));await assert.rejects(s.note('u2',a.activities[0].id,{text:'intrusion'}));await s.note('u1',a.activities[0].id,{text:'Mi nota',rpe:4,fatigue:3});await s.sync('u1');await s.drain(20);assert.equal((await s.status('u1')).activities.length,1);p.setRun({...run,name:'Nombre corregido',distance:1500});const event={subscription_id:42,owner_id:1,object_id:100,object_type:'activity',aspect_type:'update',event_time:Math.floor(Date.now()/1000)};await s.webhook(event);await s.webhook(event);assert.equal((await db.prepare('SELECT COUNT(*) n FROM strava_jobs').bind().first()).n,1);await s.drain();a=await s.status('u1');assert.equal(a.activities[0].name,'Nombre corregido');assert.equal(a.activities[0].notes.text,'Mi nota');assert.equal(a.activities[0].distance,1.5);p.remove();await s.webhook({...event,aspect_type:'delete'});await s.drain();a=await s.status('u1');assert.equal(a.activities.length,0);assert.equal(a.orphanNotes[0].text,'Mi nota');assert.equal((await s.status('u2')).activities.length,1);});
test('OAuth binds state to user + secure cookie, consumes once and respects scopes',async()=>{const db=d1(),s=new StravaService(db,config(),provider().fetch);const url=new URL(await s.begin('u1',{includePrivate:true},'cookie'));assert(url.searchParams.get('scope').includes('activity:read_all'));const state=url.searchParams.get('state');await assert.rejects(s.finish('u2',state,'cookie','code','read,activity:read'));await assert.rejects(s.finish('u1',state,'wrong','code','read,activity:read'));await s.finish('u1',state,'cookie','code','read,activity:read');await assert.rejects(s.finish('u1',state,'cookie','code','read,activity:read'));assert.equal((await s.status('u1')).privateAccess,false);});
test('refresh persists rotated credentials, expired access-only fails honestly',async()=>{const db=d1(),cfg=config(),p=provider(),s=new StravaService(db,cfg,p.fetch);await s.saveConnection('u1','1',{accessToken:'expired',refreshToken:'old-refresh',expiresAt:1},'oauth',['activity:read']);const c=await s.connection('u1');assert.equal(await s.access(c),'renewed-access');const tokens=await open((await s.connection('u1')).cipher,cfg.STRAVA_TOKEN_KEY,'u1');assert.equal(tokens.refreshToken,'rotated-refresh');assert(tokens.expiresAt>1);await s.saveConnection('u2','2',{accessToken:'expired',refreshToken:null,expiresAt:1},'token',[]);assert.equal((await s.status('u2')).state,'authorization_expired');await assert.rejects(s.access(await s.connection('u2')));await assert.rejects(rotateTokens({accessToken:'expired'},{},p.fetch));});
test('disconnect cancels jobs and in-flight writes, rejects duplicate athlete',async()=>{const db=d1(),cfg=config(),p=provider(),s=new StravaService(db,cfg,p.fetch);await s.ownToken('u1','user-one-token',{});const connection=await s.connection('u1');await assert.rejects(s.ownToken('u2','user-one-token',{}));assert.equal(await s.connection('u2'),null);await s.disconnect('u1');await s.cacheRun(connection,run);await s.drain();assert.equal((await s.status('u1')).activities.length,0);assert.equal((await s.status('u1')).state,'disconnected');assert.equal((await db.prepare('SELECT COUNT(*) n FROM strava_jobs').bind().first()).n,0);});
test('seven day expiry is enforced, policy blocks analysis and missing backend blocks imports',async()=>{const db=d1(),cfg=config(),s=new StravaService(db,cfg,provider().fetch);await s.ownToken('u1','user-one-token',{});await s.drain(10);await db.prepare('UPDATE strava_cache SET expires_at=1').bind().run();const a=await s.status('u1');assert.equal(a.activities.length,0);assert.equal(a.policy.analysis,false);assert.equal((await db.prepare('SELECT COUNT(*) n FROM strava_cache').bind().first()).n,0);const disabled=new StravaService(db,{...cfg,STRAVA_RETENTION_JOB_ENABLED:'false'},provider().fetch);await assert.rejects(disabled.begin('u2',{},'cookie'));await assert.rejects(disabled.ownToken('u2','user-two-token',{}));});
test('rate limits use global budgets and backoff without leaking provider bodies',async()=>{const db=d1(),cfg=config(),s=new StravaService(db,cfg,async()=>new Response('sensitive-token-body',{status:429,headers:{'retry-after':'120'}}));await s.saveConnection('u1','1',{accessToken:'user-one-token',refreshToken:null,expiresAt:null},'token',[]);await s.sync('u1');await s.drain();const jobs=await db.prepare('SELECT * FROM strava_jobs').bind().all();assert.equal(jobs.results[0].attempts,1);assert(jobs.results[0].due>=Math.floor(Date.now()/1000)+115);assert.equal((await s.status('u1')).state,'rate_limited');assert(!JSON.stringify(await s.status('u1')).includes('sensitive-token-body'));});
test('a rejected refresh token is reported as expired authorization',async()=>{await assert.rejects(rotateTokens({accessToken:'expired',refreshToken:'revoked'},config(),async()=>new Response('{}',{status:400})),e=>e.status===401&&e.message==='authorization_expired');});
