'use client';
import React,{useState} from 'react';
import {previewActivityImport,receivePersonalActivities} from '../lib/activity-import.mjs';
import {distanceText,durationText} from '../lib/session-instructions.mjs';
import type {FollowupState,FollowupActivity} from './activity-followup';
export default function ActivityImport({state,onSave,busy,onReceived}:{state:FollowupState,onSave:(next:unknown)=>Promise<boolean>,busy:boolean,onReceived?:(activity:FollowupActivity)=>void}){
 const [input,setInput]=useState<unknown>(null),[selected,setSelected]=useState<number[]>([]),[consent,setConsent]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const rows=input?previewActivityImport(state,input):[],ready=rows.filter(r=>r.status==='ready');
 async function load(file:File){setError('');setMessage('');setConsent(false);try{if(file.size>2000000)throw Error('El archivo supera 2 MB.');const parsed=JSON.parse(await file.text()),preview=previewActivityImport(state,parsed);setInput(parsed);setSelected(preview.filter(r=>r.status==='ready').map(r=>r.index));}catch(e){setInput(null);setError(e instanceof Error?e.message:String(e));}}
 return <details className="panel spaced personal-import"><summary>Recibir actividades de un archivo propio</summary><p>Importa un JSON personal con distancias en km y tiempos en segundos. Las actividades actualizan tus estadísticas; las incompletas solicitan sensaciones. Revisa esta lista antes de guardarlas.</p><label>Archivo de actividades<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)load(file);e.target.value='';}}/></label>
  <details><summary>Formato del archivo</summary><pre>{JSON.stringify({activities:[{id:'reloj-123',startedAt:'2026-10-02T22:30:00Z',timezone:'Europe/Madrid',distance:5,seconds:1800,type:'easy',rpe:3,fatigue:2,pain:'none',terrain:'asphalt',temperature:18,notes:'Mi registro'}]},null,2)}</pre><p>Puedes usar una fecha local «AAAA-MM-DD» en lugar de startedAt. La hora de inicio debe incluir zona u offset. Cada vuelta admite kind (warmup, work, recovery, cooldown), distance, seconds y recuperación. Omite lo que no sepas; no se rellena con sensaciones inventadas.</p></details>
  {Boolean(input)&&<><p>{ready.length} nuevas · {rows.filter(r=>r.status==='duplicate').length} duplicadas · {rows.filter(r=>r.status==='invalid').length} con errores.</p>{rows.map(row=><div className="import-row" key={row.index}>{row.status==='ready'&&row.activity?<label className="check-label"><input type="checkbox" checked={selected.includes(row.index)} onChange={e=>setSelected(e.target.checked?[...selected,row.index]:selected.filter(n=>n!==row.index))}/>{row.activity.date} · {distanceText(row.activity.distance)} · {durationText(row.activity.seconds)} · {row.activity.timezone}</label>:<p>Registro {row.index+1}: {row.reason}</p>}</div>)}<label className="check-label spaced"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Confirmo que son archivos propios de mi dispositivo y autorizo su uso para estadísticas y seguimiento en Zancada. No proceden de la API de Strava.</label><button className="primary spaced" disabled={busy||!consent||!selected.length} onClick={async()=>{setError('');try{const result=receivePersonalActivities(state,input,{consent,selectedIndices:selected});if(await onSave(result.state)){const received=result.state.activities.find((a:FollowupActivity)=>a.id===result.received[0]);if(received)onReceived?.(received);setInput(null);setMessage(`${result.received.length} actividades guardadas en sus fechas locales. Los ajustes requieren tu aceptación.`);}}catch(e){setError(e instanceof Error?e.message:String(e));}}}>Guardar actividades seleccionadas</button></>}
  {message&&<p role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
 </details>;
}
