'use client';
import React,{useState} from 'react';
import {parseActivityFile,configureActivityFile,combineActivityFiles,previewActivityImport,receivePersonalActivities,detectCsvUnits,IMPORT_LIMITS} from '../lib/activity-import.mjs';
import {activityTimeLabel} from '../lib/activity-source.mjs';
import {distanceText,durationText} from '../lib/session-instructions.mjs';
import type {FollowupState,FollowupActivity} from './activity-followup';
type Document=Awaited<ReturnType<typeof parseActivityFile>>;
type Config=Document['configuration']&{mapping?:Record<string,string>,units?:Record<string,string|null>,decimal?:string,dateOrder?:string,ambiguity?:string,layout?:string,runningConfirmed?:boolean};
type Decision={index:number,action:string,targetId?:string,fillMissing?:boolean};
const coreFields=[['startedAt','Fecha y hora de inicio'],['date','Fecha local (si no hay inicio)'],['clock','Hora local separada'],['sport','Deporte'],['distance','Distancia'],['movingTime','Tiempo en movimiento'],['elapsedTime','Tiempo transcurrido con pausas'],['timerTime','Tiempo de cronómetro'],['recordedTime','Duración de significado desconocido']];
const otherFields=[['id','Identificador de actividad'],['timezone','Zona horaria de cada fila'],['avgHR','Pulsaciones medias'],['maxHR','Pulsaciones máximas'],['elevation','Desnivel positivo'],['temperature','Temperatura'],['cadence','Cadencia'],['power','Potencia'],['notes','Notas'],['lapIndex','Número de vuelta'],['lapKind','Papel de la vuelta'],['recordKind','Fila de resumen o vuelta']];
const timeUnits=[['s','Segundos'],['clock','mm:ss o hh:mm:ss'],['min','Minutos'],['ms','Milisegundos'],['h','Horas']];
const unitText=(unit:string|null)=>({km:'km',m:'metros',mi:'millas',s:'segundos',clock:'mm:ss o hh:mm:ss',min:'minutos',ms:'milisegundos',h:'horas'}[unit||'']||'sin confirmar');
export default function ActivityImport({state,onSave,busy,onReceived}:{state:FollowupState,onSave:(next:unknown)=>Promise<boolean>,busy:boolean,onReceived?:(activity:FollowupActivity)=>void}){
 const [documents,setDocuments]=useState<Document[]>([]),[configs,setConfigs]=useState<Config[]>([]),[input,setInput]=useState<ReturnType<typeof combineActivityFiles>|null>(null),[selected,setSelected]=useState<number[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[consent,setConsent]=useState(false),[loading,setLoading]=useState(false),[errors,setErrors]=useState<string[]>([]),[message,setMessage]=useState('');
 const rows=input?previewActivityImport(state,input):[],ready=rows.filter(r=>r.status==='ready'),activeDecisions=decisions.filter(d=>d.action!=='skip'),locked=busy||loading;
 function update(index:number,value:Partial<Config>){setConfigs(configs.map((c,i)=>i===index?{...c,...value}:c));setInput(null);setSelected([]);setDecisions([]);setConsent(false);}
 async function load(files:File[]){setErrors([]);setMessage('');setInput(null);setConsent(false);setSelected([]);setDecisions([]);setLoading(true);try{
  if(!files.length||files.length>IMPORT_LIMITS.files)throw Error('Selecciona hasta 10 archivos a la vez.');if(files.some(f=>f.size>IMPORT_LIMITS.fileBytes))throw Error('Cada archivo admite hasta 10 MB.');if(files.reduce((n,f)=>n+f.size,0)>IMPORT_LIMITS.batchBytes)throw Error('El conjunto supera 30 MB.');
  const results=await Promise.allSettled(files.map(async file=>parseActivityFile({name:file.name,data:await file.arrayBuffer()},{timezone:state.profile?.timezone||'Europe/Madrid'}))),good:Document[]=[],issues:string[]=[];
  results.forEach((r,i)=>{if(r.status==='fulfilled')good.push(r.value);else issues.push(`${files[i].name}: ${r.reason instanceof Error?r.reason.message:String(r.reason)}`);});setDocuments(good);setConfigs(good.map(d=>({...d.configuration,units:{...d.units},confirmed:false})));setErrors(issues);
 }catch(error){setDocuments([]);setConfigs([]);setErrors([error instanceof Error?error.message:String(error)]);}finally{setLoading(false);}}
 function prepare(){setErrors([]);setMessage('');try{const prepared=documents.map((d,i)=>configureActivityFile(d,configs[i])),combined=combineActivityFiles(prepared),preview=previewActivityImport(state,combined);setInput(combined);setSelected(preview.filter(r=>r.status==='ready').map(r=>r.index));setDecisions([]);setConsent(false);}catch(error){setInput(null);setErrors([error instanceof Error?error.message:String(error)]);}}
 function decide(index:number,change:Partial<Decision>){const before=decisions.find(d=>d.index===index)||{index,action:'skip'};setDecisions([...decisions.filter(d=>d.index!==index),{...before,...change}]);}
 return <details className="panel spaced personal-import"><summary>Recibir actividades de un archivo propio</summary><p>Selecciona TCX, CSV, FIT o JSON de tu dispositivo. Confirma unidades y zona, revisa las actividades y decide qué guardar. Se conservan las medidas originales y los tiempos distintos; las ausencias se muestran sin rellenarlas.</p>
  <label>Archivos de actividades<input type="file" multiple accept=".tcx,.csv,.fit,.json,application/json,text/csv,application/xml" disabled={locked} onChange={e=>{const files=Array.from(e.target.files||[]);if(files.length)load(files);e.target.value='';}}/></label><p className="helper">Hasta 10 archivos, 10 MB cada uno y 30 MB en conjunto; 500 actividades, 1.000 vueltas por actividad y 20.000 puntos por archivo. FIT verifica su integridad antes de leerlo.</p>{loading&&<p role="status">Leyendo archivos…</p>}
  <details><summary>Formatos y tiempos admitidos</summary><p>TCX recupera actividades Running, vueltas y sensores. TotalTimeSeconds se conserva como tiempo registrado; no equivale automáticamente a movimiento. FIT utiliza el SDK oficial de Garmin y mantiene por separado movimiento, cronómetro y tiempo transcurrido cuando existen. CSV admite una actividad por fila, vueltas agrupadas por identificador o resumen y vueltas en el mismo archivo.</p><p>JSON conserva el formato anterior: distancia en km, seconds en movimiento y elapsedSeconds con pausas. También admite vueltas y medidas opcionales. Los archivos comprimidos y otros deportes se excluyen. No se calcula un tiempo en movimiento a partir de posiciones o velocidad.</p><pre>{JSON.stringify({activities:[{id:'reloj-123',startedAt:'2026-10-02T22:30:00Z',timezone:'Europe/Madrid',distance:5,seconds:1800,elapsedSeconds:1920,type:'easy',notes:'Mi registro'}]},null,2)}</pre></details>
  {documents.map((d,index)=>{const config=configs[index],mapping=config.mapping||{},units=config.units||{},setUnit=(field:string,value:string)=>update(index,{units:{...units,[field]:value},confirmed:false}),column=(field:string,label:string)=><label key={field}>{label}<select disabled={locked} value={mapping[field]??''} onChange={e=>{const next={...mapping,[field]:e.target.value},detected=d.csv?detectCsvUnits(d.csv.headers,next,d.csv.rows):{};update(index,{mapping:next,units:{...units,...Object.fromEntries(Object.entries(detected).filter(([,v])=>v!=null))},confirmed:false});}}><option value="">No presente / sin asignar</option>{d.csv?.headers.map((h:string,i:number)=><option key={i} value={String(i)}>{h}</option>)}</select></label>;
   return <fieldset className="spaced" key={`${d.hash}-${index}`} disabled={locked}><legend>{d.name} · {d.format.toUpperCase()}</legend><label>Zona horaria para la fecha local<input value={config.timezone} onChange={e=>update(index,{timezone:e.target.value,confirmed:false})}/></label><p className="helper">Usa una zona como Europe/Madrid. Un instante UTC u offset del archivo se conserva; esta zona determina su fecha local. Si el archivo no trae zona, confirma dónde se realizó.</p>
    {d.format==='csv'?<><div className="table-scroll"><table><caption>Primeras filas del archivo</caption><thead><tr>{d.csv?.headers.map((h:string,i:number)=><th key={i}>{h}</th>)}</tr></thead><tbody>{d.csv?.sample.map((r:string[],i:number)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><p>Separador detectado: {d.csv?.delimiter===';'?'punto y coma':d.csv?.delimiter==='\t'?'tabulación':'coma'}. Revisa el mapeo; las columnas sin asignar se conservan como originales.</p><div className="form-grid">{coreFields.map(([field,label])=>column(field,label))}</div><details className="spaced"><summary>Otras métricas y vueltas</summary><div className="form-grid">{otherFields.map(([field,label])=>column(field,label))}</div></details>
     <label>Contenido de las filas<select value={config.layout} onChange={e=>update(index,{layout:e.target.value,confirmed:false})}><option value="activities">Una actividad por fila</option><option value="laps">Una vuelta por fila, agrupada por identificador</option><option value="mixed">Una fila de resumen y sus vueltas por identificador</option></select></label><p className="helper">Para vueltas, asigna el identificador. En formato mixto, «Tipo de fila» debe indicar activity/summary o lap. El papel work/recovery solo se usa si el archivo lo declara; no se deduce de su velocidad.</p>
     <div className="form-grid"><label>Separador decimal<select value={config.decimal} onChange={e=>update(index,{decimal:e.target.value,confirmed:false})}><option value=".">Punto: 5.25</option><option value=",">Coma: 5,25</option></select></label><label>Formato de fecha<select value={config.dateOrder} onChange={e=>update(index,{dateOrder:e.target.value,confirmed:false})}><option value="iso">AAAA-MM-DD / ISO</option><option value="dmy">DD/MM/AAAA</option></select></label><label>Hora repetida en cambio de horario<select value={config.ambiguity} onChange={e=>update(index,{ambiguity:e.target.value,confirmed:false})}><option value="reject">Pedir aclaración si es ambigua</option><option value="earlier">Confirmo la primera ocurrencia</option><option value="later">Confirmo la segunda ocurrencia</option></select></label></div>
     {(!mapping.sport||mapping.sport==='')&&<label className="check-label"><input type="checkbox" checked={!!config.runningConfirmed} onChange={e=>update(index,{runningConfirmed:e.target.checked,confirmed:false})}/>Confirmo que todas las filas son de running.</label>}
    </>:null}
    {['csv','json'].includes(d.format)?<div className="form-grid"><label>Unidad de distancia<select value={units.distance||''} onChange={e=>setUnit('distance',e.target.value)}><option value="">Confirmar unidad</option><option value="km">Kilómetros</option><option value="m">Metros</option><option value="mi">Millas</option></select></label>{(d.format==='json'?['time']:['movingTime','elapsedTime','timerTime','recordedTime'].filter(field=>mapping[field]!=null&&mapping[field]!=='')).map(field=><label key={field}>Unidad: {field==='time'?'tiempos JSON':coreFields.find(([key])=>key===field)?.[1]}<select value={units[field]||''} onChange={e=>setUnit(field,e.target.value)}><option value="">Confirmar unidad</option>{timeUnits.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}{d.format==='csv'&&mapping.elevation!=null&&<label>Unidad del desnivel<select value={units.elevation||'m'} onChange={e=>setUnit('elevation',e.target.value)}><option value="m">Metros</option><option value="ft">Pies</option></select></label>}{d.format==='csv'&&mapping.temperature!=null&&<label>Unidad de temperatura<select value={units.temperature||'c'} onChange={e=>setUnit('temperature',e.target.value)}><option value="c">°C</option><option value="f">°F</option></select></label>}</div>:<p>Unidades del formato: distancia en {unitText(d.units.distance)}, tiempos en {unitText(d.units.time)}. Se conservan antes de convertir a km y segundos.</p>}
    <label className="check-label spaced"><input type="checkbox" checked={!!config.confirmed} onChange={e=>update(index,{confirmed:e.target.checked})}/>Confirmo unidades, significado de los tiempos, mapeo y zona de este archivo.</label>
   </fieldset>;
  })}
  {!!documents.length&&<button className="spaced" disabled={locked} onClick={prepare}>Preparar vista previa</button>}
  {input&&<><p>{ready.length} nuevas · {rows.filter(r=>r.status==='duplicate').length} duplicadas · {rows.filter(r=>r.status==='excluded').length} excluidas · {rows.filter(r=>r.status==='invalid').length} con errores.</p>{!input.confirmed&&<p className="notice">La vista previa está disponible. Confirma la configuración de cada archivo y vuelve a prepararla antes de guardar.</p>}
   {rows.map(row=>{const a=row.activity,decision=decisions.find(d=>d.index===row.index),existing=state.activities.find(v=>v.id===row.duplicateId);return <article className="import-row spaced" key={row.index}><b>{row.fileName||'Archivo'} · registro {row.index+1}</b>{a?<><p>{a.date} · {distanceText(a.distance)} · {durationText(a.seconds)} {activityTimeLabel(a)} · {a.terrain==='treadmill'?'cinta · ':''}{a.timezone}</p><p className="helper">Distancia original: {a.original?.distance?.value??'Total derivado de vueltas'} {a.original?.distance?.unit||''}. Inicio original: {a.original?.startedAt||a.startedAt||'No presente'}. Movimiento: {a.movingSeconds!=null?durationText(a.movingSeconds):'No presente'}; cronómetro: {a.timerSeconds!=null?durationText(a.timerSeconds):'No presente'}; transcurrido: {a.elapsedSeconds!=null?durationText(a.elapsedSeconds):'No presente'}.</p><p>{a.laps.length} vueltas utilizables · {a.samples?.length||0} muestras · FC media {a.avgHR??'ausente'} · FC máxima {a.maxHR??'ausente'}.</p>{a.notes&&<p>Notas del archivo: {a.notes}</p>}{row.missing?.length>0&&<p className="helper">{row.missing.join(' ')}</p>}{row.warnings?.map((warning:string,i:number)=><p className="helper" key={i}>{warning}</p>)}{row.status==='ready'&&<label className="check-label"><input type="checkbox" disabled={locked} checked={selected.includes(row.index)} onChange={e=>setSelected(e.target.checked?[...selected,row.index]:selected.filter(n=>n!==row.index))}/>Guardar como carrera nueva</label>}</>:null}
    {row.status!=='ready'&&<p>{row.reason}</p>}{row.status==='duplicate'&&<><label>Qué hacer con este duplicado<select disabled={locked} value={decision?.action||'skip'} onChange={e=>decide(row.index,{action:e.target.value,targetId:row.duplicateId,fillMissing:false})}><option value="skip">Omitir; conservar el registro existente</option><option value="link">Vincular archivo al registro existente</option>{!row.exact&&<option value="separate">Confirmo que es otra carrera distinta</option>}</select></label>{decision?.action==='link'&&<><p>Se conserva {existing?.date||a?.date}, su distancia, tiempo, asociación y notas: {existing?.notes||'sin notas'}. El archivo se adjunta como evidencia propia; no suma una segunda carrera.</p><label className="check-label"><input type="checkbox" checked={!!decision.fillMissing} disabled={locked} onChange={e=>decide(row.index,{fillMissing:e.target.checked})}/>Completar solo métricas ausentes con el archivo. Mantener las medidas principales y las notas del registro.</label></>}</>}
   </article>;})}
   <label className="check-label spaced"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/>Confirmo que son archivos propios de mi dispositivo y autorizo su uso para estadísticas y seguimiento en Zancada. No proceden de la API ni de una exportación de Strava.</label><button className="primary spaced" disabled={locked||!consent||!input.confirmed||!selected.length&&!activeDecisions.length} onClick={async()=>{setErrors([]);try{const result=receivePersonalActivities(state,input,{consent,selectedIndices:selected,duplicateDecisions:decisions});if(await onSave(result.state)){const received=result.state.activities.find((a:FollowupActivity)=>a.id===(result.received[0]||result.linked[0]));if(received)onReceived?.(received);setInput(null);setDocuments([]);setConfigs([]);setMessage(`${result.received.length} carreras nuevas y ${result.linked.length} archivos vinculados. Se conservaron las notas y el calendario; los ajustes requieren tu aceptación.`);}}catch(error){setErrors([error instanceof Error?error.message:String(error)]);}}}>Guardar actividades seleccionadas</button>
  </>}
  {message&&<p role="status">{message}</p>}{errors.map((error,i)=><p className="error" role="alert" key={i}>{error}</p>)}
 </details>;
}
