'use client';
import React,{useEffect,useState} from 'react';
import {chatReply} from '../lib/coach-chat.mjs';
import {hasAIConsent,withAIConsent} from '../lib/coach-consent.mjs';
import {manualContext} from '../lib/ai-coach.mjs';
type State=Parameters<typeof manualContext>[0];
export type CoachMessage={q:string,answer:string,mode?:string,model?:string,notice?:string,proposal?:{id:string,reason:string,changes:{before:{date:string,type:string,distance:number,seconds:number},after:{date:string,type:string,distance:number,seconds:number}}[]}|null};
type ModelStatus={available:boolean,state:string,model?:string,reason:string,generationVerified?:boolean};
export default function CoachChat({state,revision,demo,busy,dirty,onSave,messages,onMessages,question,onQuestion}:{state:State,revision:number,demo:boolean,busy:boolean,dirty:boolean,onSave:(value:State)=>Promise<boolean>,messages:CoachMessage[],onMessages:(messages:CoachMessage[])=>void,question:string,onQuestion:(value:string)=>void}){
 const [status,setStatus]=useState<ModelStatus|null>(null),[mode,setMode]=useState('rules'),[waiting,setWaiting]=useState(false),[error,setError]=useState('');
 const allowed=hasAIConsent(state),locked=busy||waiting;
 async function check(){if(demo)return;try{const response=await fetch('/api/coach');if(!response.ok)throw Error();setStatus(await response.json() as ModelStatus);}catch{setStatus({available:false,state:'unavailable',reason:'No se pudo comprobar el modelo; puedes usar las reglas locales.'});}}
 useEffect(()=>{let cancelled=false;if(!demo)fetch('/api/coach').then(async response=>{if(response.ok&&!cancelled)setStatus(await response.json() as ModelStatus);}).catch(()=>{if(!cancelled)setStatus({available:false,state:'unavailable',reason:'Estado del modelo no disponible.'});});return()=>{cancelled=true;};},[demo]);
 async function ask(q:string){if(!q.trim()||locked)return;setError('');setWaiting(true);try{
  let result:Awaited<ReturnType<typeof chatReply>>;
  if(mode==='rules'||demo||dirty)result=await chatReply(state,{question:q,mode:'rules'});
  else{const response=await fetch('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,mode,revision})});const body=await response.json() as Awaited<ReturnType<typeof chatReply>>&{error?:string};if(!response.ok)throw Error(body.error||'No se pudo consultar el modelo.');result=body;}
  onMessages([...messages,{q,answer:result.answer,mode:result.mode,model:result.model||undefined,notice:result.notice||undefined,proposal:result.proposal}]);onQuestion('');
 }catch(e){const result=await chatReply(state,{question:q,mode:'rules'});onMessages([...messages,{q,answer:result.answer,mode:'rules',notice:(e instanceof Error?e.message:'Error de consulta.')+' Respuesta por reglas locales; no se obtuvo una respuesta del modelo.',proposal:null}]);onQuestion('');}finally{setWaiting(false);}}
 return <section className="panel chat" aria-label="Chat de entrenamiento"><div className="section-heading"><h2>Chat de entrenamiento</h2><span className="pill">{demo?'Demostración · reglas locales':mode==='rules'?'Reglas locales · sin API':status?.available&&allowed?'Ollama disponible · se verifica al responder':'Modelo sin comprobar'}</span></div><p>Usa tu perfil, objetivo, calendario y registros manuales. El motor decide las sesiones. Puedes preguntar sin servicios externos.</p>
 <label>Modo del chat<select value={mode} disabled={locked||demo} onChange={e=>setMode(e.target.value)}><option value="rules">Reglas locales, sin modelo</option><option value="ollama" disabled={!status?.available||!allowed}>Modelo local Ollama</option></select></label>
 <p className="helper">{status?.reason||'Comprobando si hay un modelo local disponible…'} {status?.model&&`Modelo configurado: ${status.model}.`} <button className="text-button" disabled={locked||demo} onClick={check}>Comprobar modelo</button></p>
 <label className="check-label spaced"><input type="checkbox" checked={allowed} disabled={locked||demo} onChange={async e=>{const enable=e.target.checked;if(await onSave(withAIConsent(state,enable))&&!enable)setMode('rules');}}/>Autorizo usar mi perfil deportivo, plan, sensaciones y registros manuales con el modelo local o las herramientas de Zancada para ChatGPT. Excluye Strava y archivos externos. Puedo retirarlo aquí.</label>
 <p className="helper">No se envían nombre, correo, tokens ni notas libres. El modelo local selecciona explicaciones comprobables y puede proponer mover, reducir o descansar; no escribe el calendario.</p>
 {dirty&&<p className="notice">Hay cambios sin guardar: se responde por reglas locales hasta guardarlos.</p>}
 <div className="suggestions">{['¿Cuál es mi próxima sesión?','¿Qué hago hoy si estoy cansado?','He perdido una sesión, ¿qué hago?'].map(q=><button key={q} disabled={locked} onClick={()=>ask(q)}>{q}</button>)}</div>
 <div className="messages" aria-live="polite">{messages.map((m,i)=><div key={i}><div className="question">{m.q}</div><div className="answer"><div><small>{m.mode==='ollama'?`Modelo local ${m.model} · respuesta comprobada`:'Respuesta por reglas locales'}</small><p style={{whiteSpace:'pre-wrap'}}>{m.answer}</p>{m.notice&&<p className="helper">{m.notice}</p>}{m.proposal&&<div className="detail-note"><b>Propuesta concreta, sin aplicar</b><p>{m.proposal.reason}</p>{m.proposal.changes.map((c,n)=><p key={n}>{c.before.date}: {c.before.type} · {c.before.distance??0} km · {Math.round(c.before.seconds/60)} min → {c.after.date}: {c.after.type} · {c.after.distance??0} km · {Math.round(c.after.seconds/60)} min.</p>)}<button disabled={locked||state.proposals.some((v:{id:string})=>v.id===m.proposal?.id)} onClick={async()=>{if(await onSave({...state,proposals:[...state.proposals,m.proposal]}))setError('');}}>Guardar propuesta para revisar en Mi plan</button><p className="helper">Guardar la propuesta no cambia sesiones. Allí puedes aceptar, rechazar y deshacer.</p></div>}</div></div></div>)}</div>
 <form className="chat-input" onSubmit={e=>{e.preventDefault();ask(question.trim());}}><label className="sr-only" htmlFor="question">Tu pregunta</label><input id="question" placeholder="Pregunta sobre tu entrenamiento…" maxLength={2000} value={question} onChange={e=>onQuestion(e.target.value)} required/><button disabled={locked} type="submit" className="primary">{waiting?'Consultando…':'Preguntar'}</button></form>{error&&<p role="alert" className="error">{error}</p>}
 <details className="spaced"><summary>Instalar un modelo local opcional</summary><p>Solo en la versión PC. Instala <a href="https://ollama.com/download/windows" target="_blank" rel="noreferrer">Ollama para Windows</a> (Windows 10 22H2 o posterior; al menos 4 GB para la aplicación, más el modelo). Desactiva la nube en Ollama con la variable de usuario <code>OLLAMA_NO_CLOUD=1</code> y reinicia Ollama. Descarga el modelo con <code>ollama pull llama3.2:3b</code> y comprueba <code>ollama list</code>. Se ejecuta en CPU si no hay GPU compatible; el rendimiento depende del equipo.</p><p>Activa <code>ZANCADA_OLLAMA_ENABLED=true</code> y <code>OLLAMA_MODEL=llama3.2:3b</code> en <code>.dev.vars</code> y reinicia Zancada. «Comprobar modelo» verifica el servicio y la instalación; una respuesta válida verifica la generación. No se descarga ni instala nada automáticamente. Consulta <a href="https://docs.ollama.com/windows" target="_blank" rel="noreferrer">requisitos oficiales</a>.</p><p>Ollama usa recursos de tu PC y no exige facturación de API. Una suscripción de ChatGPT no concede acceso gratuito a la API. En despliegue remoto esta opción local permanece desactivada.</p></details></section>;
}
