'use client';
import React from 'react';
import {dailyFocus} from '../lib/daily-focus.mjs';
import {TYPES,pace,dateObj} from '../lib/engine.mjs';
import {sessionTotals,distanceText} from '../lib/session-instructions.mjs';
type State=Parameters<typeof dailyFocus>[0];
type Session=ReturnType<typeof dailyFocus>['session'];
const date=(d:string)=>dateObj(d).toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'short',timeZone:'UTC'});
const type=(s:Session)=>TYPES[s.type as keyof typeof TYPES];
export default function DailyFocus({state,onOpen,onWeek,onHistory,onGoal}:{state:State,onOpen:(s:Session)=>void,onWeek:()=>void,onHistory:()=>void,onGoal:()=>void}){
 const focus=dailyFocus(state),s=focus.session;
 const title=focus.caution==='pain'?'Hoy: pausa y revisa las molestias':focus.kind==='workout'?`Hoy: ${type(s)}`:focus.kind==='completed'?'Entrenamiento de hoy registrado':focus.kind==='skipped'?'Hoy has omitido la sesión':focus.kind==='recorded'?'Carrera registrada hoy':focus.kind==='finished'?'Has terminado este bloque':'Hoy: descanso';
 return <section className="next-card daily-focus" aria-label="Qué entreno hoy"><div className="next-header"><span className="eyebrow">QUÉ ENTRENO HOY</span><span className="next-date">{date(focus.date)}</span></div><h2>{title}</h2>
 {focus.caution&&<p className="daily-caution" role="status">{focus.caution==='pain'?'Has indicado molestias que afectan la zancada. Evita correr y valora la situación con un profesional antes de retomar.':focus.caution==='mild'?'Has indicado molestias leves. Evita intensidad y revisa la alternativa antes de salir.':'Has indicado fatiga alta. Revisa la alternativa suave o descansa si no mejora.'} El calendario conserva la sesión aceptada hasta que revises un cambio.</p>}
 {focus.kind==='workout'&&s?<><span className="pill on-dark">{s.type==='race'?'Día de la carrera':s.distance!=null?distanceText(s.distance):sessionTotals(s).duration}</span><p>{s.purpose}</p><div className="daily-reason"><b>Por qué me toca</b><p>{s.trainingFocus?.reason||s.phase?.reason||'Forma parte de la preparación aceptada, según tu base y disponibilidad.'}</p></div><div className="next-metrics"><div><strong>{sessionTotals(s).duration}</strong><small>{sessionTotals(s).label}</small></div><div><strong>{s.range?`${pace(s.range[0])}–${pace(s.range[1])} min/km`:`Esfuerzo ${s.rpe}/10`}</strong><small>{s.conversation||'Sigue el esfuerzo y las instrucciones de cada bloque.'}</small></div></div>{focus.unlinkedToday.length>0&&<p className="daily-caution">Ya hay una carrera guardada hoy que no completa esta sesión. Revisa su asociación antes de entrenar otra vez. <button className="lime" onClick={onHistory}>Revisar actividad de hoy</button></p>}<button className="lime" onClick={()=>onOpen(s)}>Ver entrenamiento</button></>:<><p>{focus.kind==='completed'?'El registro actualiza calendario y estadísticas. Comprueba qué indica para tu siguiente sesión.':focus.kind==='skipped'?'No se traslada ni se acumula la carga omitida. Retoma la siguiente sesión según tus sensaciones.':focus.kind==='recorded'?'El registro suma estadísticas. Su asociación y propósito se revisan con los datos disponibles; no implica hacer otra carrera hoy.':focus.kind==='finished'?'Revisa tu objetivo para preparar el siguiente bloque. Tus actividades e historial se conservan.':s?.purpose||'No hay una sesión pautada para hoy. Recupera sin adelantar ni compensar entrenamientos.'}</p><button className="lime" onClick={focus.kind==='finished'?onGoal:focus.runs.length?onHistory:onWeek}>{focus.kind==='finished'?'Revisar siguiente objetivo':focus.runs.length?'Ver qué cambia tras mi carrera':'Ver mi semana'}</button></>}
 {focus.next&&<div className="daily-next"><b>Después: {type(focus.next)}</b><p>{date(focus.next.date)} · {focus.next.distance!=null?distanceText(focus.next.distance):sessionTotals(focus.next).duration}</p><button className="text-button" onClick={()=>onOpen(focus.next)}>Consultar próxima sesión</button></div>}
 </section>;
}
