'use client';
import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ShieldCheck} from 'lucide-react';
import {DAYS,TYPES,today,addDays,uid,blankProfile,profileErrors,feasibility,qualityEligibility,pace,duration,seconds,timeZone} from '../lib/engine.mjs';
import {buildPlanPreview,acceptPlanPreview,weekSummary} from '../lib/training.mjs';
import {updateAvailability} from '../lib/profile-evidence.mjs';
import {StravaConnectCard,defaultStravaSettings,stravaAction} from './strava-panel';
import {Field,Select,TextArea,terrainOptions,painOptions,goalOptions} from './fields';
import {BaseQuestions,RaceQuestions,MarkQuestions,CareQuestions,SportQuestions,OwnHistoryConfirmation,RunnerSummary,AnswerWarnings} from './runner-questions';
const STEPS=['Tu cuenta','Strava','Objetivo','Experiencia','Disponibilidad','Cuidados','Tu plan'];
const KEY='zancada-onboarding';
const fmt=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'});
// Wizard progress is a per-browser convenience so the Strava OAuth redirect can resume it. The profile is only saved on the server at the end.
function stored(owner:string){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v?.owner===owner?v:null;}catch{return null;}}
function keep(owner:string,step:number,draft:any){try{localStorage.setItem(KEY,JSON.stringify({owner,step,draft}));}catch{}}
export function clearOnboarding(){try{localStorage.removeItem(KEY);}catch{}}
export default function Onboarding({account,state,save,busy,revision=null,strava,refreshStrava,onFullForm,onDemo}:{account?:{name:string,email:string},state:any,save:(next:any)=>Promise<any>,busy:boolean,revision?:number|null,strava:any,refreshStrava:()=>Promise<void>,onFullForm:()=>void,onDemo:()=>void}){
 const owner=account?.email||'local';
 const [step,setStep]=useState(0),[draft,setDraft]=useState<any>(()=>({...blankProfile(),name:account?.name?.split(/[ @]/)[0]||'',timezone:timeZone()})),[errors,setErrors]=useState<string[]>([]),[stravaSettings,setStravaSettings]=useState<any>(defaultStravaSettings),[stravaBusy,setStravaBusy]=useState(false),[stravaMessage,setStravaMessage]=useState(''),[gentle,setGentle]=useState(false),[reviewing,setReviewing]=useState(false);
 useEffect(()=>{const saved=stored(owner);if(saved){setDraft({...blankProfile(),...saved.draft,timezone:timeZone()});setStep(saved.step);}const url=new URL(window.location.href),code=url.searchParams.get('strava');if(code){url.searchParams.delete('strava');window.history.replaceState({},'',url.toString());setStravaMessage(code==='connected'?'Strava conectado. Tus carreras se consultan por separado en Ajustes, sin mezclarse con los registros del plan.':'No se completó la autorización con Strava. Puedes reintentarlo o continuar sin conectar.');if(saved)setStep(Math.max(saved.step,1));}},[owner]);
 useEffect(()=>{keep(owner,step,draft);},[owner,step,draft]);
 const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const setGoal=(g:any)=>setDraft((d:any)=>({...d,goal:{...d.goal,...g}}));
 const preview=useMemo<any>(()=>{if(step!==6)return null;try{return buildPlanPreview({...state,profile:draft},{conservative:gentle},today(),{revision});}catch(e:any){return {error:e.message};}},[step,draft,gentle,state,revision]);
 function check(s:number){
  const e:string[]=[],g=draft.goal;
  if(s===2){if(['nonstop','time','race'].includes(g.type)&&g.distance!==''&&g.distance!=null&&!(+g.distance>0&&+g.distance<=100))e.push('Revisa la distancia objetivo, o déjala vacía si no lo sabes.');if(g.date&&g.date<=today())e.push('La fecha objetivo debe ser posterior a hoy.');if(g.time&&!(seconds(g.time)>0))e.push('Tiempo deseado: usa mm:ss o hh:mm:ss.');}
  if(s===4){e.push(...profileErrors(draft).filter(x=>/deportes|Disponibilidad/.test(x)));if(!draft.days.length)e.push('Selecciona al menos un día.');}
  const all=profileErrors(draft);
  if(s===0)e.push(...all.filter(x=>/adultos/.test(x)));
  if(s===3)e.push(...all.filter(x=>/Kilómetros|Tirada|Ritmo|FC|marcas|Frecuencia|Constancia|Pausa|weekly|longest|easy/.test(x)));
  if(s>=5)e.push(...all);
  return [...new Set(e)];
 }
 function go(to:number){if(to>step){const e=check(step);setErrors(e);if(e.length)return;}setErrors([]);setStep(to);window.scrollTo?.({top:0});}
 async function connect(){setStravaBusy(true);setStravaMessage('');keep(owner,2,draft);try{await stravaAction('connect',stravaSettings);}catch(e:any){setStravaMessage(e.message);}finally{setStravaBusy(false);}}
 async function finish(){try{const e=check(6);setErrors(e);if(e.length||!preview||preview.error)return;const withProfile={...state,profile:draft};if(await save(acceptPlanPreview(withProfile,preview,today(),revision))){clearOnboarding();await refreshStrava();}}catch(e){setErrors([e instanceof Error?e.message:'Vuelve a calcular la propuesta.']);}}
 const toggleDay=(d:number,on:boolean)=>setDraft((v:any)=>updateAvailability(v,d,on));
 const setMark=(i:number,k:string,val:any)=>set('marks',draft.marks.map((m:any,j:number)=>i===j?{...m,[k]:val}:m));
 let viability:any=null;try{viability=step===6?(preview?.plan?.viability||feasibility(draft)):null;}catch{}
 return <div className="wizard">
  <div className="wizard-head"><span className="eyebrow">CONFIGURACIÓN INICIAL · PASO {step+1} DE {STEPS.length}</span><h1>{['Bienvenido a Zancada','Tus actividades','¿Qué quieres conseguir?','Tu punto de partida','¿Cuándo puedes entrenar?','Cuidados y preferencias','Tu plan personal'][step]}</h1><ol className="wizard-steps" aria-label="Progreso">{STEPS.map((s,i)=><li key={s} className={i===step?'current':i<step?'done':''}><button type="button" disabled={i>step} onClick={()=>go(i)} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={13}/>:i+1}</span>{s}</button></li>)}</ol></div>
  {errors.length>0&&<div className="alert error" role="alert"><div>{errors.map(e=><p key={e}>{e}</p>)}</div></div>}
  <section className="panel wizard-body">
   {step===0&&<><div className="account-card"><ShieldCheck size={26}/><div><b>{account?.name||'Tu cuenta'}</b><small>{account?.email}</small></div></div><p>Tu cuenta de Zancada es la cuenta personal con la que has iniciado sesión. Tu perfil, objetivos, carreras y planes se guardan en un espacio propio vinculado a ella. El servidor comprueba tu identidad en cada lectura y escritura, así que nadie más puede ver ni cambiar tus datos.</p><Field label="¿Cómo quieres que te llamemos?" value={draft.name} maxLength={60} onChange={(v:any)=>set('name',v)}/><Field label="Edad (opcional)" type="number" min="18" max="100" value={draft.age} onChange={(v:any)=>set('age',v)} hint="El plan está pensado para personas adultas."/><p className="helper">Zona horaria detectada: {draft.timezone}. Tus sesiones y registros usan las fechas de esta zona. ¿No es tu cuenta? <a href="/signout-with-chatgpt?return_to=%2F" target="_top">Cerrar sesión</a></p></>}
   {step===1&&<>{stravaMessage&&<p className="notice" role="status">{stravaMessage}</p>}<StravaConnectCard data={strava} busy={stravaBusy||busy} settings={stravaSettings} setSettings={setStravaSettings} onConnect={connect} onSkip={()=>go(2)}/></>}
   {step===2&&<><div className="goal-options">{goalOptions.map(([id,title,sub])=><label key={id} className={draft.goal.type===id?'chosen':''}><input type="radio" name="wizard-goal" checked={draft.goal.type===id} onChange={()=>setGoal({type:id,intent:id==='unknown'?'unknown':id==='time'?'improve':id==='nonstop'?'nonstop':id==='race'?(draft.goal.intent||'finish'):'finish',distance:id==='unknown'?'':draft.goal.distance,date:['start','routine','unknown'].includes(id)?'':draft.goal.date,time:['start','routine','nonstop','unknown'].includes(id)?'':draft.goal.time})}/><b>{title}</b><small>{sub}</small></label>)}</div>
    <div className="form-grid spaced">{['nonstop','time','race'].includes(draft.goal.type)&&<>{draft.goal.type==='time'?<Select label="Distancia" value={draft.goal.distance} onChange={(v:any)=>setGoal({distance:v===''?'':+v})} options={[["",'No lo sé'],...(draft.goal.distance&&![5,10,21.1,42.2].includes(+draft.goal.distance)?[[draft.goal.distance,`${draft.goal.distance} km`]]:[]),[5,'5 km'],[10,'10 km'],[21.1,'Media maratón · 21,1 km'],[42.2,'Maratón · 42,2 km']]}/>:<Field label="Distancia (km)" placeholder="No lo sé" hint="Sin distancia, la preparación es general y provisional." type="number" min="1" max="100" step="0.1" value={draft.goal.distance} onChange={(v:any)=>setGoal({distance:v})}/>}<Field label={draft.goal.type==='race'?'Fecha de la carrera':'Fecha objetivo (opcional)'} type="date" min={addDays(today(),1)} max={addDays(today(),364)} hint="Vacío = No lo sé. Sin fecha, prepararemos un bloque general sin día de carrera." value={draft.goal.date} onChange={(v:any)=>setGoal({date:v})}/></>}</div>
    <RaceQuestions profile={draft} onChange={setDraft}/>{['start','routine'].includes(draft.goal.type)&&<p className="helper">Prepararemos un bloque de 12 semanas centrado en la constancia.</p>}</>}
   {step===3&&<><div className="form-grid"><Select label="Experiencia corriendo" value={draft.experience} onChange={(v:any)=>set('experience',v)} options={[['beginner','Estoy empezando'],['regular','Corro con regularidad'],['experienced','Tengo experiencia'],['unknown','No lo sé']]}/><Field label="Kilómetros semanales actuales" type="number" min="0" max="250" step="0.1" placeholder="No lo sé" value={draft.weeklyKm} onChange={(v:any)=>set('weeklyKm',v)} hint="Media de las últimas 3–4 semanas. Déjalo vacío si no lo sabes: empezaremos con correr y caminar."/><Field label="Tirada más larga reciente (km)" type="number" min="0" max="150" step="0.1" placeholder="No lo sé" value={draft.longest} onChange={(v:any)=>set('longest',v)}/><Field label="Ritmo habitual suave (min/km, opcional)" placeholder="No lo sé · 6:30" value={draft.easyPace} onChange={(v:any)=>set('easyPace',v)} hint="Un ritmo al que puedes conversar. 6:30 min/km ≈ 9,2 km/h."/></div>
    <BaseQuestions profile={draft} onChange={setDraft}/><OwnHistoryConfirmation state={state} profile={draft} onChange={setDraft}/><h3 className="spaced">Marcas recientes (opcional)</h3><p>Añade solo referencias reales. Una marca incompleta o estimada se conserva sin fijar ritmos. Si no recuerdas un dato, déjalo vacío.</p>{draft.marks.map((m:any,i:number)=><details key={m.id} className="spaced" open><summary>Referencia {i+1}{m.distance?' · '+m.distance+' km':''}</summary><div className="form-grid"><Field label="Fecha" type="date" max={today()} hint="Vacío = No lo sé" value={m.date||''} onChange={(v:any)=>setMark(i,'date',v)}/><Field label="Distancia (km)" type="number" min="0.1" max="100" step="0.1" placeholder="No lo sé" value={m.distance??''} onChange={(v:any)=>setMark(i,'distance',v)}/><Field label="Tiempo" placeholder="No lo sé · 26:30" value={m.time||''} onChange={(v:any)=>setMark(i,'time',v)}/></div><MarkQuestions mark={m} onChange={(next:any)=>set('marks',draft.marks.map((v:any,j:number)=>i===j?next:v))}/><button type="button" className="text-button" onClick={()=>set('marks',draft.marks.filter((_:any,j:number)=>i!==j))}>Quitar marca</button></details>)}<button type="button" disabled={draft.marks.length>=20} onClick={()=>set('marks',[...draft.marks,{id:uid(),date:'',distance:'',time:'',context:'unknown',measurement:'unknown',effort:'unknown',terrain:'unknown',elevation:'',elapsedTime:''}])}>Añadir una marca de referencia</button>
    <details className="spaced"><summary>Pulsaciones (opcional)</summary><div className="form-grid"><Field label="FC en reposo (ppm)" type="number" min="30" max="140" value={draft.restHR} onChange={(v:any)=>set('restHR',v)}/><Field label="FC máxima (ppm)" type="number" min="60" max="240" value={draft.maxHR} onChange={(v:any)=>set('maxHR',v)}/><Select label="Origen" value={draft.hrSource} onChange={(v:any)=>set('hrSource',v)} options={[["unknown",'No lo sé'],['measured','Medidos'],['estimated','Estimados']]}/></div><p className="helper">No estimamos la FC máxima por la edad. Sin ambos valores medidos no mostramos zonas; no inventamos umbrales.</p></details></>}
   {step===4&&<><p>Marca los días en que puedes entrenar y el tiempo máximo de cada uno. Indica el tiempo total de entrenamiento disponible ese día; los otros deportes que declares consumen parte de ese tiempo.</p><div className="availability">{[1,2,3,4,5,6,0].map(d=><div key={d} className={draft.days.includes(d)?'available':''}><label className="check-label"><input type="checkbox" checked={draft.days.includes(d)} onChange={e=>toggleDay(d,e.target.checked)}/>{DAYS[d]}</label>{draft.days.includes(d)&&<Field label="Minutos" type="number" min="15" max="360" placeholder="No lo sé" value={draft.minutes[d]??''} onChange={(v:any)=>set('minutes',{...draft.minutes,[d]:v})}/>}</div>)}</div>
    {draft.days.length>0&&<div className="form-grid spaced"><Select label="Días de carrera por semana" value={draft.trainingDays} onChange={(v:any)=>set('trainingDays',+v)} options={draft.days.map((_:any,i:number)=>[i+1,`${i+1} ${i?'días':'día'}`])} hint="Puedes dejar días disponibles como margen o para fuerza."/><Select label="Día preferido para la tirada larga" value={draft.longDay} onChange={(v:any)=>set('longDay',+v)} options={draft.days.map((d:number)=>[d,DAYS[d]])}/></div>}<SportQuestions profile={draft} onChange={setDraft}/></>}
   {step===5&&<><div className="form-grid"><Select label="Molestias actuales" value={draft.pain} onChange={(v:any)=>set('pain',v)} options={[["unknown",'No lo sé'],...painOptions]} hint="Con molestias no programamos intensidad; si afectan la zancada, el plan propone pausa."/><Select label="Terreno habitual" value={draft.terrain} onChange={(v:any)=>set('terrain',v)} options={terrainOptions}/><TextArea label="Lesiones previas (opcional)" value={draft.injuries} onChange={(v:any)=>set('injuries',v)}/><TextArea label="Restricciones o indicaciones profesionales (opcional)" value={draft.restrictions} onChange={(v:any)=>set('restrictions',v)}/></div><p className="helper">Las notas escritas se muestran en cada sesión, pero el plan no las interpreta clínicamente.</p>
    <CareQuestions profile={draft} onChange={setDraft}/><label className="check-label spaced"><input type="checkbox" checked={draft.strength} onChange={e=>setDraft({...draft,strength:e.target.checked,strengthDay:draft.days.includes(+draft.strengthDay)?draft.strengthDay:draft.days[0]})}/> Añadir 25 minutos de fuerza complementaria</label>{draft.strength&&<Select label="Día de fuerza" value={draft.strengthDay} onChange={(v:any)=>set('strengthDay',+v)} options={draft.days.map((d:number)=>[d,DAYS[d]])} hint="Debe ser un día disponible en el que no corras."/>}
    <label className="check-label spaced"><input type="checkbox" checked={gentle} onChange={e=>setGentle(e.target.checked)}/> Prefiero empezar con menos carga (−15 %)</label></>}
   {step===6&&<><RunnerSummary profile={draft} onEdit={s=>{setReviewing(true);go(s);}}/>{preview?.error?<div className="alert error">{preview.error}</div>:preview&&<>
    <div className={`viability ${viability?.cautious?'cautious':''}`}><b>{viability?.cautious?'Tu meta necesita revisión':'Meta orientativamente razonable'}</b>{viability?.notes.map((n:string)=><p key={n}>{n}</p>)}{viability?.alternatives?.length>0&&<div className="alternatives"><small>ALTERNATIVAS</small>{viability.alternatives.map((a:any,i:number)=><button type="button" key={`${a.kind}-${i}`} onClick={()=>setGoal(a.goal)}>{a.text}</button>)}</div>}</div>
    <div className="summary-metrics spaced"><div><b>{preview.plan.sessions.filter((s:any)=>s.type!=='rest').length}</b><small>Sesiones hasta {preview.plan.sessions.some((s:any)=>s.type==='race')?'el día de la carrera':'el final del bloque'}</small></div><div><b>{Math.ceil(preview.plan.racePreparation.totalWeeks)}</b><small>Semanas</small></div><div><b>{draft.weeklyKm!==''&&draft.weeklyKm!=null?`${preview.plan.racePreparation.initialWeeklyKm} km`:'Sin confirmar'}</b><small>Base semanal de partida</small></div></div>
    <h3 className="spaced">Tus primeras dos semanas</h3><div className="preview-weeks">{[0,7].map(o=>{const w=weekSummary({...state,plan:preview.plan},addDays(today(),o));return <div key={o}><b>Semana del {fmt(w.start)}</b><span>{w.plannedKm.toLocaleString('es-ES')} km previstos{w.sessions.some((s:any)=>s.distance==null&&s.type!=='rest')?' + sesiones por tiempo':''}</span><small>{w.phase?.label||'Adaptación'}</small><div>{w.sessions.map((s:any)=><span className={`pill ${s.type}`} key={s.id}>{fmt(s.date)} · {TYPES[s.type as keyof typeof TYPES]} · {s.distance!=null?`${s.distance.toLocaleString('es-ES')} km`:s.durationUnknown?'duración sin estimar':duration(s.seconds)}</span>)}</div></div>;})}</div>
    {preview.plan.sessions.find((s:any)=>s.type==='race')&&<p className="notice">El {fmt(preview.plan.sessions.find((s:any)=>s.type==='race').date)} aparecerá como <b>Día de la carrera</b> · {draft.goal.distance!==''&&draft.goal.distance!=null?`${(+draft.goal.distance).toLocaleString('es-ES')} km`:'distancia sin confirmar'}. Las semanas previas reducen carga.</p>}
    <h3 className="spaced">Qué entrenamientos incluye y por qué</h3><ul className="uses-list">{qualityEligibility(preview.plan.basis.profile,preview.plan).filter((r:any)=>r.included||!['walk','strength'].includes(r.type)).map((r:any)=><li key={r.type} className={r.included?'ok':'pending'}><span aria-hidden="true">{r.included?'✓':'·'}</span><div><b>{TYPES[r.type as keyof typeof TYPES]}</b>{r.included?` · ${r.count} ${r.count===1?'sesión':'sesiones'}`:' · todavía no'}<small>{r.reason}</small></div></li>)}</ul>
    <p className="helper">{preview.plan.method} No garantiza resultados.{preview.plan.sessions.find((s:any)=>s.basePace)?` Ritmo de referencia: ${pace(preview.plan.sessions.find((s:any)=>s.basePace).basePace)} min/km.`:''}</p></>}</>}
   {step>=2&&step<=5&&<AnswerWarnings profile={draft}/>}
  </section>
  <div className="wizard-actions">{step>0?<button type="button" onClick={()=>go(step-1)}><ArrowLeft size={17}/>Atrás</button>:<button type="button" className="text-button" onClick={onDemo}>Ver una demostración</button>}
   {step===0&&<button type="button" className="text-button" onClick={onFullForm}>Usar el formulario completo</button>}
   {reviewing&&step>=2&&step<6&&<button type="button" onClick={()=>{const e=check(6);setErrors(e);if(!e.length)go(6);}}>Volver al resumen</button>}
   {step<6&&step!==1&&<button type="button" className="primary" onClick={()=>go(step+1)}>Continuar<ArrowRight size={17}/></button>}
   {step===6&&<button type="button" className="primary" disabled={busy||!preview||!!preview.error} onClick={finish}>{busy?'Guardando…':'Crear mi plan'}<Check size={17}/></button>}</div>
 </div>;
}
