'use client';
import React from 'react';
import {DAYS,uid,seconds,pace} from '../lib/engine.mjs';
import {recentTraining} from '../lib/training.mjs';
import {Field,Select,terrainOptions} from './fields';
type Props={profile:any,onChange:(next:any)=>void};
export function BaseQuestions({profile:p,onChange}:Props){const set=(key:string,value:any)=>onChange({...p,[key]:value});return <div className="spaced"><h3>Constancia reciente</h3><div className="form-grid">
 <Select label="Días que has corrido por semana últimamente" value={p.recentFrequency??''} onChange={(v:any)=>set('recentFrequency',v)} options={[["",'No lo sé'],...[0,1,2,3,4,5,6,7].map(n=>[n,`${n} días`])]} hint="Últimas cuatro semanas. No aumentamos varios días de golpe para llegar a la carrera."/>
 <Select label="¿Cómo ha sido tu continuidad?" value={p.consistency||'unknown'} onChange={(v:any)=>set('consistency',v)} options={[["unknown",'No lo sé'],['continuous','He corrido sin pausas importantes'],['intermittent','He corrido de forma intermitente'],['returning','Retomo tras dos o más semanas sin correr']]}/>
 {p.consistency!=='returning'&&<Field label="Semanas consecutivas con esta rutina" type="number" min="0" max="520" value={p.consistentWeeks} placeholder="No lo sé" onChange={(v:any)=>set('consistentWeeks',v)} hint="Sin confirmar constancia, la base sigue siendo provisional. Se revisará con tus registros."/>}
 </div><p className="helper">Puedes dejar vacíos volumen, tirada y ritmo si no los sabes. La propuesta comenzará por tiempo y esfuerzo, con límites conservadores; no asumirá que ya estás preparado para la distancia.</p></div>}
export function RaceQuestions({profile:p,onChange}:Props){if(!['race','time','nonstop'].includes(p.goal.type))return null;const set=(key:string,value:any)=>onChange({...p,goal:{...p.goal,[key]:value,...(key==='intent'&&value!=='time'?{time:''}:{})}});return <div className="form-grid spaced">
 {p.goal.type!=='nonstop'&&<Select label="Prioridad en la carrera" value={p.goal.intent|| (p.goal.time?'time':p.goal.type==='time'?'improve':'finish')} onChange={(v:any)=>set('intent',v)} options={[["finish",'Terminar con control'],['improve','Mejorar mi marca'],['time','Buscar un tiempo concreto']]} hint="El tiempo deseado se evalúa; no impone ritmos de entrenamiento."/>}
 <Select label="Terreno de la carrera" value={p.goal.terrain||'asphalt'} onChange={(v:any)=>set('terrain',v)} options={[["asphalt",'Asfalto / llano'],['trail','Senderos o montaña'],['unknown','No lo sé']]} hint="En senderos, desnivel o terreno desconocido, la carrera se orienta por esfuerzo."/>
 <Field label="Desnivel positivo de la carrera (m)" type="number" min="0" max="15000" value={p.goal.elevation??''} placeholder="No lo sé" onChange={(v:any)=>set('elevation',v)} hint="No extrapolamos una marca llana a una carrera con desnivel importante."/>
 </div>}
export function MarkQuestions({mark:m,onChange}:{mark:any,onChange:(next:any)=>void}){const set=(key:string,value:any)=>onChange({...m,[key]:key==='effort'&&value==='legacy'?undefined:value});return <div className="form-grid spaced">
 <Select label="Esfuerzo de esta marca" value={m.effort||'legacy'} onChange={(v:any)=>set('effort',v)} options={[...(m.effort?[]:[["legacy",'Marca anterior: uso provisional, confirmar esfuerzo']]),["unknown",'No lo sé / pendiente de confirmar'],['race','Carrera o prueba a esfuerzo máximo sostenible'],['controlled','Entrenamiento exigente, con margen'],['easy','Rodaje suave']]} hint="Solo una prueba confirmada orienta ritmos rápidos. Un rodaje no demuestra tu máximo rendimiento."/>
 <Select label="Terreno de la marca" value={m.terrain||'asphalt'} onChange={(v:any)=>set('terrain',v)} options={terrainOptions}/>
 <Field label="Desnivel positivo de la marca (m, opcional)" type="number" min="0" max="15000" value={m.elevation??''} placeholder="No lo sé" onChange={(v:any)=>set('elevation',v)}/>
 <Field label="Tiempo total con pausas (opcional)" value={m.elapsedTime||''} placeholder="No lo sé" onChange={(v:any)=>set('elapsedTime',v)} hint="El tiempo principal es en movimiento. Si hubo pausas importantes, no usamos esa marca para predecir tiempos."/>
 </div>}
export function CareQuestions({profile:p,onChange}:Props){const set=(key:string,value:any)=>onChange({...p,[key]:value});return <div className="spaced"><div className="form-grid">
 <Field label="Fatiga habitual estos días (0–10)" type="number" min="0" max="10" value={p.fatigue??''} placeholder="No lo sé" onChange={(v:any)=>set('fatigue',v)} hint="7 o más reduce la carga inicial y suprime intensidad."/>
 <Select label="Recuperación entre entrenamientos" value={p.recovery||'unknown'} onChange={(v:any)=>set('recovery',v)} options={[["unknown",'No lo sé'],['good','Suelo llegar recuperado'],['poor','Acumulo cansancio o duermo mal']]} hint="Es tu percepción; no una medición de recuperación."/>
 </div><label className="check-label spaced"><input type="checkbox" checked={!!p.recentInjury} onChange={e=>set('recentInjury',e.target.checked)}/> Estoy volviendo tras una lesión reciente (últimos tres meses)</label><p className="helper">Una lesión reciente elimina la intensidad y reduce la propuesta inicial. Las restricciones que escribas deben revisarse con quien te las indicó.</p></div>}
export function SportQuestions({profile:p,onChange}:Props){const sports=p.otherSports||[],set=(next:any[])=>onChange({...p,otherSports:next});return <details className="spaced"><summary>Fuerza, CrossFit y otros deportes que ya practico</summary><p>Indica cada sesión semanal habitual. No sumará kilómetros de running. Un deporte exigente reserva ese día y evita intensidad de carrera alrededor; las sesiones suaves también se consideran en el reparto de tiempo.</p>{sports.map((s:any,i:number)=><div key={s.id} className="form-grid spaced">
 <Select label="Deporte" value={s.type} onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,type:v}:a))} options={[["strength",'Fuerza'],['crossfit','CrossFit'],['cycling','Ciclismo'],['other','Otro deporte']]}/>
 <Select label="Día" value={s.day} onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,day:+v}:a))} options={[1,2,3,4,5,6,0].map(d=>[d,DAYS[d]])}/>
 <Field label="Minutos" type="number" min="10" max="600" value={s.minutes} onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,minutes:v}:a))}/>
 <Select label="Intensidad habitual" value={s.intensity} onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,intensity:v}:a))} options={[["easy",'Suave'],['moderate','Moderada'],['hard','Exigente / piernas cargadas']]}/>
 <button type="button" className="text-button danger" onClick={()=>set(sports.filter((_:any,j:number)=>j!==i))}>Quitar deporte</button>
 </div>)}<button type="button" className="spaced" disabled={sports.length>=14} onClick={()=>set([...sports,{id:uid(),type:'strength',day:2,minutes:45,intensity:'moderate'}])}>Añadir deporte habitual</button></details>}
export function OwnHistoryConfirmation({state,profile,onChange}:Props&{state:any}){const evidence=recentTraining({...state,profile});if(evidence.count<6||evidence.activeWeeks<3)return <p className="helper">Strava se muestra por separado: sus condiciones actuales impiden usar esos datos para analizar la base o alimentar IA. Puedes planificar con tus respuestas y tus registros propios de Zancada.</p>;return <details className="notice spaced"><summary>Ya tienes registros propios: confirmar mi base</summary><p>{evidence.activeWeeks}/4 semanas con registros · mediana {evidence.medianWeeklyKm} km/semana · tirada {evidence.longest} km{evidence.easyPace?` · ritmo suave observado ${pace(evidence.easyPace)} min/km`:''}. Confirma que has registrado todas las carreras de esas cuatro semanas antes de utilizar estos valores.</p><button type="button" onClick={()=>onChange({...profile,weeklyKm:evidence.medianWeeklyKm,longest:evidence.longest,recentFrequency:Math.min(7,Math.round(evidence.medianFrequency)),consistentWeeks:evidence.activeWeeks,...(evidence.easyPace?{easyPace:pace(Math.ceil(evidence.easyPace/5)*5)}:{})})}>Confirmo historial completo; usar mi base registrada</button></details>}
