'use client';
import React from 'react';
import {DAYS,uid,pace,today} from '../lib/engine.mjs';
import {recentTraining} from '../lib/training.mjs';
import {profileReport,profileWarnings} from '../lib/profile-report.mjs';
import {goalPriority} from '../lib/profile-evidence.mjs';
import {Field,Select,terrainOptions} from './fields';
type Props={profile:any,onChange:(next:any)=>void};
const origins=[['unknown','No lo sé'],['measured','Medido / registrado'],['estimated','Estimado de memoria']];
export function BaseQuestions({profile:p,onChange}:Props){const set=(key:string,value:any)=>onChange({...p,[key]:value});return <div className="spaced"><h3>Constancia reciente</h3><div className="form-grid">
 <Select label="Días que has corrido por semana últimamente" value={p.recentFrequency??''} onChange={(v:any)=>set('recentFrequency',v)} options={[["",'No lo sé'],...[0,1,2,3,4,5,6,7].map(n=>[n,`${n} días`])]} hint="Últimas cuatro semanas. No aumentamos varios días de golpe para llegar a la carrera."/>
 <Select label="¿Cómo ha sido tu continuidad?" value={p.consistency||'unknown'} onChange={(v:any)=>set('consistency',v)} options={[["unknown",'No lo sé'],['continuous','He corrido sin pausas importantes'],['intermittent','He corrido de forma intermitente'],['returning','Retomo tras dos o más semanas sin correr']]}/>
 {p.consistency!=='returning'&&<Field label="Semanas consecutivas con esta rutina" type="number" min="0" max="520" value={p.consistentWeeks} placeholder="No lo sé" onChange={(v:any)=>set('consistentWeeks',v)} hint="Sin confirmar constancia, la base sigue siendo provisional. Se revisará con tus registros."/>}
 {(p.consistency==='returning'||p.consistency==='intermittent'||+p.pauseWeeks>0)&&<Field label="Pausa más larga en las últimas ocho semanas" type="number" min="0" max="8" value={p.pauseWeeks??''} placeholder="No lo sé" onChange={(v:any)=>set('pauseWeeks',v)} hint="Semanas completas sin correr. Dos o más reducen la base; cuatro o más aumentan esa reducción."/>}
 {p.weeklyKm!==''&&p.weeklyKm!=null&&<><Select label="Origen de los kilómetros semanales" value={p.weeklySource||'unknown'} onChange={(v:any)=>set('weeklySource',v)} options={origins} hint="Una estimación se conserva como tal y comienza con menos carga."/><Select label="Variación entre las últimas semanas" value={p.weeklyTrend||'unknown'} onChange={(v:any)=>set('weeklyTrend',v)} options={[["unknown",'No lo sé'],['stable','Volumen parecido cada semana'],['increasing','He aumentado bastante'],['decreasing','He reducido bastante'],['variable','Semanas muy distintas']]} hint="Si la carga está cambiando, empezamos con menos volumen y aplazamos intensidad."/></>}
 {+p.longest>0&&<><Field label="Fecha de la tirada reciente" type="date" max={today()} value={p.longestDate||''} onChange={(v:any)=>set('longestDate',v)} hint="Déjala vacía si no lo sabes. Una tirada de más de seis semanas tiene menos peso."/><Select label="Origen de la distancia de la tirada" value={p.longestSource||'unknown'} onChange={(v:any)=>set('longestSource',v)} options={origins}/><Select label="¿Cómo resultó esa tirada?" value={p.longestResult||'unknown'} onChange={(v:any)=>set('longestResult',v)} options={[["unknown",'No lo sé'],['comfortable','Cómoda, terminé con margen'],['hard','Muy difícil o acabé agotado'],['pain','Con molestias']]} hint="Una tirada difícil reduce el límite inicial; con molestias se pospone intensidad."/></>}
 {(p.easyPace||+p.weeklyKm>0||+p.recentFrequency>0)&&<>{p.easyPace&&<Select label="Origen del ritmo cómodo" value={p.easySource||'unknown'} onChange={(v:any)=>set('easySource',v)} options={origins} hint="El ritmo estimado tiene un margen mayor; no es un umbral medido."/>}<Field label="Esfuerzo en tus rodajes suaves (0–10)" type="number" min="0" max="10" value={p.easyEffort??''} placeholder="No lo sé" onChange={(v:any)=>set('easyEffort',v)}/><Select label="¿Puedes conversar en un rodaje suave?" value={p.easyConversation||'unknown'} onChange={(v:any)=>set('easyConversation',v)} options={[["unknown",'No lo sé'],['yes','Sí, frases completas con comodidad'],['short','Solo frases cortas'],['no','Apenas algunas palabras']]} hint="Aunque no conozcas el ritmo, tu esfuerzo y conversación deciden si posponemos intensidad. Por encima de 4/10 o sin conversación, no usamos ese ritmo como suave."/></>}
 </div><p className="helper">Puedes dejar vacíos volumen, tirada y ritmo si no los sabes. La propuesta comenzará por tiempo y esfuerzo, con límites conservadores; no asumirá que ya estás preparado para la distancia.</p></div>}
export function RaceQuestions({profile:p,onChange}:Props){if(!['race','time','nonstop'].includes(p.goal.type))return null;const set=(key:string,value:any)=>onChange({...p,goal:{...p.goal,[key]:value}});return <div className="form-grid spaced">
 {p.goal.type!=='nonstop'&&<Select label="Prioridad en la carrera" value={p.goal.intent==='unknown'?'unknown':goalPriority(p)} onChange={(v:any)=>set('intent',v)} options={[["unknown",'No lo sé: empezar con resistencia cómoda'],['finish','Terminar con control'],['nonstop','Correr sin parar'],['improve','Mejorar mi marca']]} hint="Terminar o correr sin parar prioriza carrera cómoda. Mejorar marca permite calidad solo con una base estable."/>}
 {(p.goal.intent==='improve'||p.goal.intent==='time'||p.goal.time||p.goal.type==='time')&&<Field label="Tiempo deseado (opcional)" placeholder="No lo sé · 55:00 o 1:45:00" value={p.goal.time||''} onChange={(v:any)=>set('time',v)} hint="Un tiempo concreto se contrasta con tu marca; nunca fija por sí solo los ritmos de entrenamiento."/>}
 <Select label="Flexibilidad para una meta alternativa" value={p.goal.flexibility||'unknown'} onChange={(v:any)=>set('flexibility',v)} options={[["unknown",'No lo sé; mostrar opciones'],['any','Puedo revisar tiempo, distancia o fecha'],['time','Cambiar tiempo o priorizar terminar'],['date','Cambiar solo la fecha'],['distance','Cambiar solo la distancia'],['fixed','Quiero mantener la meta y revisar mi preparación']]} hint="Filtra las alternativas propuestas. Ninguna modifica tu meta sin que la elijas."/>
 <Select label="Terreno de la carrera" value={p.goal.terrain||'asphalt'} onChange={(v:any)=>set('terrain',v)} options={[["asphalt",'Asfalto / llano'],['trail','Senderos o montaña'],['unknown','No lo sé']]} hint="En senderos, desnivel o terreno desconocido, la carrera se orienta por esfuerzo."/>
 <Field label="Desnivel positivo de la carrera (m)" type="number" min="0" max="15000" value={p.goal.elevation??''} placeholder="No lo sé" onChange={(v:any)=>set('elevation',v)} hint="No extrapolamos una marca llana a una carrera con desnivel importante."/>
 </div>}
export function MarkQuestions({mark:m,onChange}:{mark:any,onChange:(next:any)=>void}){const set=(key:string,value:any)=>onChange({...m,[key]:key==='effort'&&value==='legacy'?undefined:value});return <div className="form-grid spaced">
 <Select label="Contexto de la marca" value={m.context||'unknown'} onChange={(v:any)=>set('context',v)} options={[["unknown",'No lo sé / marca anterior sin contexto'],['competition','Competición'],['training','Entrenamiento habitual'],['test','Prueba de esfuerzo máximo sostenible']]} hint="Una competición o prueba máxima comparable puede orientar rendimiento; un entrenamiento habitual no."/>
 <Select label="Origen de distancia y tiempo de la marca" value={m.measurement||'unknown'} onChange={(v:any)=>set('measurement',v)} options={origins} hint="Las marcas estimadas o sin origen confirmado se guardan, pero no fijan ritmos de rendimiento."/>
 <Select label="Esfuerzo de esta marca" value={m.effort||'legacy'} onChange={(v:any)=>set('effort',v)} options={[...(m.effort?[]:[["legacy",'Marca anterior: confirmar antes de fijar ritmos']]),["unknown",'No lo sé / pendiente de confirmar'],['race','Carrera o prueba a esfuerzo máximo sostenible'],['controlled','Entrenamiento exigente, con margen'],['easy','Rodaje suave']]} hint="Solo una prueba confirmada orienta ritmos rápidos. Un rodaje no demuestra tu máximo rendimiento."/>
 <Select label="Terreno de la marca" value={m.terrain||'unknown'} onChange={(v:any)=>set('terrain',v)} options={[["unknown",'No lo sé'],...terrainOptions]}/>
 <Field label="Desnivel positivo de la marca (m, opcional)" type="number" min="0" max="15000" value={m.elevation??''} placeholder="No lo sé" onChange={(v:any)=>set('elevation',v)}/>
 <Field label="Tiempo total con pausas (opcional)" value={m.elapsedTime||''} placeholder="No lo sé" onChange={(v:any)=>set('elapsedTime',v)} hint="El tiempo principal es en movimiento. Si hubo pausas importantes, no usamos esa marca para predecir tiempos."/>
 <Field label="Temperatura de la referencia (°C, opcional)" type="number" min="-30" max="60" value={m.temperature??''} placeholder="No lo sé" onChange={(v:string)=>set('temperature',v)}/>
 <Select label="Otras condiciones de la referencia" value={m.conditions||'unknown'} onChange={(v:string)=>set('conditions',v)} options={[['unknown','No lo sé'],['normal','Sin incidencias conocidas'],['hot','Calor relevante'],['windy','Viento relevante']]}/>
 {m.context==='training'&&<><Field label="Esfuerzo del rodaje (1–10)" type="number" min="1" max="10" value={m.rpe??''} onChange={(v:string)=>set('rpe',v)}/><Field label="Fatiga tras el rodaje (0–10)" type="number" min="0" max="10" value={m.fatigue??''} onChange={(v:string)=>set('fatigue',v)}/><Select label="Conversación durante el rodaje" value={m.conversation||'unknown'} onChange={(v:string)=>set('conversation',v)} options={[['unknown','No lo sé'],['yes','Conversación cómoda'],['short','Frases cortas'],['no','No podía conversar']]}/><Select label="Molestias en el rodaje" value={m.pain||'unknown'} onChange={(v:string)=>set('pain',v)} options={[['unknown','No lo sé'],['none','Sin molestias'],['mild','Leves'],['relevant','Afectan la zancada']]}/></>}
 </div>}
export function CareQuestions({profile:p,onChange}:Props){const set=(key:string,value:any)=>onChange({...p,[key]:value});return <div className="spaced"><div className="form-grid">
 <Field label="Fatiga habitual estos días (0–10)" type="number" min="0" max="10" value={p.fatigue??''} placeholder="No lo sé" onChange={(v:any)=>set('fatigue',v)} hint="7 o más reduce la carga inicial y suprime intensidad."/>
 <Select label="Recuperación entre entrenamientos" value={p.recovery||'unknown'} onChange={(v:any)=>set('recovery',v)} options={[["unknown",'No lo sé'],['good','Suelo llegar recuperado'],['poor','Acumulo cansancio o duermo mal']]} hint="Es tu percepción; no una medición de recuperación."/>
 <Select label="Restricción para correr" value={p.runningRestriction||'unknown'} onChange={(v:any)=>set('runningRestriction',v)} options={[["unknown",'No lo sé'],['none','Sin restricciones indicadas'],['no-intensity','Evitar intensidad'],['time-limit','Limitar la duración de cada sesión'],['no-running','No correr por ahora']]} hint="Este límite sí cambia el calendario. Las notas libres se conservan, pero no se interpretan automáticamente."/>
 {p.runningRestriction==='time-limit'&&<Field label="Máximo permitido por sesión (minutos)" type="number" min="1" max="360" value={p.restrictionMinutes??''} placeholder="No lo sé" onChange={(v:any)=>set('restrictionMinutes',v)} hint="Sin confirmar el límite, o si es menor de 15 minutos, se propone pausa."/>}
 </div><Select label="Vuelta tras una lesión reciente (últimos tres meses)" value={p.recentInjury?'yes':p.injuryAnswer||'unknown'} onChange={(v:any)=>onChange({...p,recentInjury:v==='yes',injuryAnswer:v})} options={[["unknown",'No lo sé'],['no','No'],['yes','Sí, estoy volviendo tras una lesión reciente']]} /><p className="helper">Una lesión reciente elimina la intensidad y reduce la propuesta inicial. Las restricciones que escribas deben revisarse con quien te las indicó.</p></div>}
export function SportQuestions({profile:p,onChange}:Props){const sports=p.otherSports||[],set=(next:any[])=>onChange({...p,otherSports:next});return <details className="spaced"><summary>Fuerza, CrossFit y otros deportes que ya practico</summary><p>Indica cada sesión semanal habitual. No sumará kilómetros de running. Un deporte exigente reserva ese día y evita intensidad de carrera alrededor; las sesiones suaves también se consideran en el reparto de tiempo.</p>{sports.map((s:any,i:number)=><div key={s.id} className="form-grid spaced">
 <Select label="Deporte" value={s.type} onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,type:v}:a))} options={[["strength",'Fuerza'],['crossfit','CrossFit'],['cycling','Ciclismo'],['other','Otro deporte']]}/>
 <Select label="Día" value={s.day} onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,day:+v}:a))} options={[1,2,3,4,5,6,0].map(d=>[d,DAYS[d]])}/>
 <Field label="Minutos" type="number" min="10" max="600" value={s.minutes} placeholder="No lo sé" onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,minutes:v}:a))}/>
 <Select label="Intensidad habitual" value={s.intensity} onChange={(v:any)=>set(sports.map((a:any,j:number)=>i===j?{...a,intensity:v}:a))} options={[["unknown",'No lo sé'],['easy','Suave'],['moderate','Moderada'],['hard','Exigente / piernas cargadas']]} hint="Si falta duración o intensidad, reservamos ese día hasta confirmarlo."/>
 <button type="button" className="text-button danger" onClick={()=>set(sports.filter((_:any,j:number)=>j!==i))}>Quitar deporte</button>
 </div>)}<button type="button" className="spaced" disabled={sports.length>=14} onClick={()=>set([...sports,{id:uid(),type:'strength',day:2,minutes:'',intensity:'unknown'}])}>Añadir deporte habitual</button></details>}
export function AnswerWarnings({profile}:{profile:any}){const warnings=profileWarnings(profile);return warnings.length?<div className="notice spaced" role="status"><b>Datos que conviene revisar</b><ul>{warnings.map(v=><li key={v}>{v}</li>)}</ul><small>Puedes continuar: se conservan tus respuestas y se aplican límites conservadores.</small></div>:null;}
export function RunnerSummary({profile,onEdit}:{profile:any,onEdit:(step:number)=>void}){const r=profileReport(profile);return <section className="runner-summary spaced" aria-label="Resumen editable del corredor"><h2>Tu punto de partida · resumen editable</h2><p>Comprueba las respuestas antes de calcular o aceptar el plan. Los datos medidos tienen el origen que has declarado; Zancada no los verifica externamente.</p>{r.rows.map(row=><div key={row.key} className="spaced"><h3>{row.title} <button type="button" className="text-button" onClick={()=>onEdit(row.step)}>Editar {row.title.toLowerCase()}</button></h3><p>{row.text}</p><small>{row.effect}</small></div>)}<div className="form-grid spaced"><div><h3>Información fiable para estimar</h3>{r.reliable.length?<ul>{r.reliable.map(v=><li key={v}>{v}</li>)}</ul>:<p>Aún no hay valores con origen medido confirmado.</p>}{r.estimated.length>0&&<><b>Información estimada o provisional</b><ul>{r.estimated.map(v=><li key={v}>{v}</li>)}</ul></>}</div><div><h3>Información ausente y precisión</h3>{r.missing.length?<ul>{r.missing.map(v=><li key={v}>{v}</li>)}</ul>:<p>Has aportado las referencias principales; los ritmos y resultados siguen siendo estimaciones.</p>}</div></div><AnswerWarnings profile={profile}/></section>}
export function OwnHistoryConfirmation({state,profile,onChange}:Props&{state:any}){const evidence=recentTraining({...state,profile});if(evidence.count<6||evidence.activeWeeks<3)return <p className="helper">Strava se muestra por separado: sus condiciones actuales impiden usar esos datos para analizar la base o alimentar IA. Puedes planificar con tus respuestas y tus registros propios de Zancada.</p>;return <details className="notice spaced"><summary>Ya tienes registros propios: confirmar mi base</summary><p>{evidence.activeWeeks}/4 semanas con registros · mediana {evidence.medianWeeklyKm} km/semana · tirada {evidence.longest} km{evidence.easyPace?` · ritmo suave observado ${pace(evidence.easyPace)} min/km`:''}. Confirma que has registrado todas las carreras de esas cuatro semanas antes de utilizar estos valores.</p><button type="button" onClick={()=>onChange({...profile,weeklyKm:evidence.medianWeeklyKm,weeklySource:'measured',longest:evidence.longest,longestSource:'measured',longestDate:evidence.longestRun?.date||'',longestResult:['mild','relevant'].includes(evidence.longestRun?.pain)?'pain':evidence.longestRun?.rpe>4?'hard':'unknown',recentFrequency:Math.min(7,Math.round(evidence.medianFrequency)),consistentWeeks:evidence.activeWeeks,...(evidence.easyPace?{easyPace:pace(Math.ceil(evidence.easyPace/5)*5),easySource:'measured',easyEffort:'',easyConversation:'unknown'}:{})})}>Confirmo historial completo; usar mi base registrada</button></details>}
