'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Play,Pause,Volume2,Timer,Check} from 'lucide-react';
import {pace,duration,today} from '../lib/engine.mjs';
export default function SessionGuide({s,onRegister}:{s:any,onRegister:any}){
 const [open,setOpen]=useState(false),[index,setIndex]=useState(0),[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),[voice,setVoice]=useState(false),[supported,setSupported]=useState(false),[total,setTotal]=useState(0);
 const clock=useRef<number|null>(null),blockElapsed=useRef(0),totalElapsed=useRef(0),announced=useRef(-1),current=s.blocks[index],done=index>=s.blocks.length;
 useEffect(()=>{setSupported('speechSynthesis' in window);return()=>{if('speechSynthesis' in window)window.speechSynthesis.cancel();};},[]);
 useEffect(()=>{blockElapsed.current=0;setElapsed(0);clock.current=running?Date.now():null;},[index]);
 useEffect(()=>{if(!running||done){clock.current=null;return;}clock.current=Date.now();const timer=setInterval(()=>{const now=Date.now(),delta=(now-(clock.current||now))/1000;clock.current=now;blockElapsed.current+=delta;totalElapsed.current+=delta;setElapsed(Math.floor(blockElapsed.current));setTotal(Math.floor(totalElapsed.current));if(!current.distance&&blockElapsed.current>=current.seconds){blockElapsed.current=0;setIndex(i=>i+1);}},250);return()=>clearInterval(timer);},[running,index,done,current]);
 useEffect(()=>{if(done){setRunning(false);return;}if(running&&voice&&supported&&announced.current!==index){announced.current=index;const speech=new SpeechSynthesisUtterance(`${current.label}. ${current.distance?`${current.distance} kilómetros.`:`${Math.round(current.seconds/60)} minutos.`} Esfuerzo ${current.effort} de diez.`);speech.lang='es-ES';window.speechSynthesis.cancel();window.speechSynthesis.speak(speech);}},[index,running,voice,supported,done,current]);
 function reset(){setRunning(false);setIndex(0);setElapsed(0);setTotal(0);blockElapsed.current=0;totalElapsed.current=0;announced.current=-1;if(supported)window.speechSynthesis.cancel();}
 if(!s.blocks.length||s.type==='race')return null;
 return <section className="session-guide spaced"><button className="primary" onClick={()=>setOpen(!open)} aria-expanded={open}><Timer size={18}/>{open?'Ocultar guía':'Seguir sesión por bloques'}</button>{open&&<div className="guide-console spaced"><div className="section-heading"><b>{done?'Guía terminada':`Bloque ${index+1} de ${s.blocks.length}`}</b><span>{duration(total)} activos</span></div>{done?<><div className="guide-done"><Check size={30}/><h3>Has terminado los bloques de la guía</h3></div><p>La guía no mide distancia, ritmo ni pulsaciones, y no completa automáticamente la sesión. Registra lo que realmente has realizado.</p>{s.type!=='strength'&&<button disabled={s.date>today()} onClick={onRegister}>Registrar mi carrera</button>}<button className="text-button" onClick={reset}>Reiniciar guía</button></>:<><h3>{current.label}</h3><div className="guide-target"><strong>{current.distance?`${current.distance.toLocaleString('es-ES')} km`:duration(Math.max(0,current.seconds-elapsed))}</strong><span>{current.targetPace?`${pace(current.targetPace)} min/km`:`Esfuerzo ${current.effort}/10`}</span></div><p>{current.distance?'Pulsa «Bloque completado» cuando alcances esta distancia en tu reloj o en la cinta.':'Cuenta atrás por tiempo; al terminar pasa al siguiente bloque.'}</p>{current.distance>0&&<small>Tiempo activo en este bloque: {duration(elapsed)}. La duración prevista es una estimación.</small>}<div className="actions spaced"><button className="lime" onClick={()=>setRunning(!running)}>{running?<Pause size={18}/>:<Play size={18}/>} {running?'Pausar':'Empezar / continuar'}</button><button disabled={!running&&elapsed===0} onClick={()=>setIndex(i=>i+1)}>{current.distance?'Bloque completado':'Saltar bloque'}</button><button className="text-button" onClick={reset}>Reiniciar</button></div></>}{supported&&<label className="check-label spaced"><input type="checkbox" checked={voice} onChange={e=>{setVoice(e.target.checked);announced.current=-1;if(!e.target.checked)window.speechSynthesis.cancel();}}/><Volume2 size={17}/> Leer instrucciones al cambiar de bloque</label>}<p className="helper">Mantén esta pantalla abierta. El navegador puede suspender la guía al bloquear el móvil. La voz depende del dispositivo. No es grabación GPS ni envío al reloj.</p></div>}</section>;
}
