'use client';
import React from 'react';
import {BLOCK_KINDS,pace} from '../lib/engine.mjs';
import {blockInstruction,conversationText,distanceText,durationText,fatigueAlternative,paceText,prescriptionSummary,prescriptionWarnings,recoveryInstruction,sessionTotals} from '../lib/session-instructions.mjs';

export type SessionBlock={label:string,kind?:string,distance:number,seconds:number,effort:number,range?:number[]|null,targetPace?:number|null,role?:string|null};
export type PrescriptionSession={type:string,date?:string,distance:number|null,seconds:number,blocks:SessionBlock[],rpe:number,range?:number[]|null,conversation?:string,durationUnknown?:boolean,reference?:string,basePace?:number|null,paceSource?:string,week?:number,progression?:string,purpose?:string,format?:{id:string,title:string,level?:string,requirements?:string[]},selectionReason?:string,substitution?:{reason:string,requestedType?:string},fit?:{reason:string},strength?:{equipment:string,rounds:number,exerciseCount:number}};
export type PrescriptionProfile={pain?:string,runningRestriction?:string,restrictionMinutes?:string|number,minutes:Record<number,string|number>,otherSports?:{day:string|number,minutes?:string|number}[],restHR?:string|number,maxHR?:string|number,hrSource?:string};

export function CalendarPrescription({s}:{s:PrescriptionSession}){
 const totals=sessionTotals(s),summary=prescriptionSummary(s),recovery=recoveryInstruction(s),warnings=prescriptionWarnings(s);
 return <span className="calendar-prescription">{warnings.length>0&&<span className="calendar-warning">Revisa las instrucciones: hay una incoherencia en esta sesión.</span>}<span className="calendar-timing">{totals.duration} · {totals.timing==='prescribed'?'prescritos':totals.timing==='unknown'?'sin estimar':'estimados'}</span>{s.type!=='rest'&&<><span className="calendar-blocks">{summary.map(row=><span key={row.kind}><b>{row.title}: </b>{row.text}</span>)}</span><span className="calendar-effort">{paceText(s.range)||'Por esfuerzo'} · E {s.rpe}/10. {s.conversation||conversationText(s.rpe,s.type)}</span>{recovery.count>0&&s.type!=='strength'&&<span className="calendar-repetitions">{recovery.workCount} repeticiones · {recovery.count} recuperaciones</span>}</>}</span>;
}

function Blocks({s,profile}:{s:PrescriptionSession,profile:PrescriptionProfile}){
 return <ol className="blocks">{(s.blocks||[]).map((b,i)=>{const info=blockInstruction({...s,profile},b);return <li key={i} className={`kind-${info.kind}`}><div><span className="block-kind">{BLOCK_KINDS[info.kind as keyof typeof BLOCK_KINDS]}</span><b>{b.label}</b><small><b>{info.measure}</b> · {info.timingText}</small><small>Esfuerzo {b.effort}/10. {info.conversation}</small>{info.pace?<><small><b>Ritmo orientativo: {info.pace}</b></small><small>Cinta: {info.speed}. En pendiente o calor, prioriza el esfuerzo.</small></>:<small>{s.type==='hills'&&b.effort>=5?'En subida no se fija ritmo en min/km.':'Sin ritmo numérico: sigue el esfuerzo y la conversación de este bloque.'}</small>}{info.hr&&<small>FC orientativa: {info.hr[0]}–{info.hr[1]} ppm · reserva cardíaca; no es un umbral medido.</small>}</div></li>;})}</ol>;
}
function Outline({s}:{s:PrescriptionSession}){return <dl className="prescription-outline">{prescriptionSummary(s).map(row=><div key={row.kind}><dt>{row.title}</dt><dd>{row.text}</dd></div>)}</dl>;}

export default function SessionPrescription({s,profile,currentProfile=profile,referenceDate,guide}:{s:PrescriptionSession,profile:PrescriptionProfile,currentProfile?:PrescriptionProfile,referenceDate?:string,guide?:React.ReactNode}){
 const totals=sessionTotals(s),warnings=prescriptionWarnings(s),alternative=fatigueAlternative({...profile,pain:currentProfile.pain,runningRestriction:currentProfile.runningRestriction,restrictionMinutes:currentProfile.restrictionMinutes,minutes:currentProfile.minutes,otherSports:currentProfile.otherSports},s,referenceDate),altTotals=sessionTotals(alternative);
 const hasHR=(s.blocks||[]).some(b=>blockInstruction({...s,profile:currentProfile},b).hr);
 return <section className="session-prescription">
  <h3>Tu sesión, paso a paso</h3>{s.format&&<div className="detail-note"><b>{s.format.title}</b><p>{s.purpose}</p>{s.selectionReason&&<p>{s.selectionReason}</p>}{s.format.level&&<p>Nivel: {s.format.level}.</p>}{s.format.requirements?.map(requirement=><p key={requirement}>{requirement}</p>)}{s.strength&&<p>{s.strength.rounds>0?<>{s.strength.rounds} ronda(s) completa(s), {s.strength.exerciseCount} ejercicios pautados. Los descansos cuentan dentro de los minutos. Puedes usar las variantes sin material aunque dispongas de banda o mancuernas.</>:<>Solo movilidad cómoda: el tiempo disponible no permite una ronda completa de fuerza. Registra los minutos y el esfuerzo que realmente realizaste.</>}</p>}</div>}{s.substitution&&<p role="status">Sesión sustituida: {s.substitution.reason}</p>}{s.fit&&<p role="status">Sesión reducida: {s.fit.reason}</p>}<Outline s={s}/>
  <div className="detail-note"><b>Total: {s.distance!=null?distanceText(s.distance):totals.duration}</b><p>{totals.label}: {totals.duration}.</p>{totals.timing==='mixed'&&<p>Tiempo prescrito: {durationText(totals.prescribedSeconds)}. El resto depende del ritmo real de los bloques por distancia.</p>}<p className="helper">{s.type==='race'?'El calentamiento y caminar tras la meta quedan fuera de la distancia oficial.':totals.matching?'✓ Los bloques suman el total: calentamiento + bloque principal + recuperaciones + vuelta a la calma.':'Revisa: los bloques no suman el total.'} {s.distance==null?'En sesiones por tiempo no se inventa una distancia.':''}</p></div>
  {warnings.map(w=><p key={w} className="error" role="alert">{w}</p>)}
  {guide}
  {s.type==='rest'?<p>No hay entrenamiento pautado para este día.</p>:<Blocks s={s} profile={currentProfile}/>}
  <div className="detail-note"><b>De qué ritmo partimos</b><p>{s.reference||'No hay una referencia suficiente para fijar ritmos: utiliza esfuerzo y conversación.'}</p>{s.basePace!=null&&s.basePace>0&&<p>{s.paceSource==='declared-easy'?'Ritmo cómodo declarado:':'Referencia normalizada a 5 km:'} {pace(s.basePace)} min/km. Cada bloque adapta esa referencia a su propósito.</p>}{s.paceSource==='declared-easy'&&<p><b>Referencia provisional:</b> parte de tu ritmo cómodo declarado, con un margen orientativo. No mide tu umbral ni prescribe ritmos rápidos desde esa respuesta.</p>}<b>Progresión · semana {(s.week||0)+1}</b><p>{s.progression||'La duración y el esfuerzo dependen del plan aceptado. No se exige correr más rápido por avanzar de semana.'}</p><p>Los rangos orientan el entrenamiento; no garantizan una precisión fisiológica ni una marca. 6:00 min/km equivale a 10 km/h.</p>{hasHR?<p>La FC se calcula con tu máxima y reposo declarados como medidos. Es una orientación por reserva cardíaca; prioriza esfuerzo y conversación.</p>:!['rest','race','strength'].includes(s.type)&&<p>Sin FC pautada: hacen falta máxima y reposo medidos y coherentes. Una media de pulsaciones no determina un ritmo exacto.</p>}</div>
  <h3>Si hoy estás cansado</h3><div className="detail-note fatigue-option"><b>{alternative.title}</b><p>{alternative.description}</p>{alternative.blocks.length>0&&<details><summary>Ver los bloques de la alternativa · {altTotals.duration} {altTotals.timing==='prescribed'?'prescritos':'estimados'}</summary><Outline s={alternative}/><Blocks s={alternative} profile={currentProfile}/><p>Total: {alternative.distance!=null?distanceText(alternative.distance):altTotals.duration}. {altTotals.label}: {altTotals.duration}. {altTotals.matching?'✓ Los bloques suman el total.':'Revisa el total.'}</p></details>}<p className="helper">Si la realizas, registra la distancia, el tiempo y el tipo que realmente has hecho. El calendario conserva la prescripción original para poder comparar.</p></div>
 </section>;
}
