import {IMPORT_LIMITS,normalizedName,numeric,distanceKm,durationSeconds,runningSport,assertPersonalProvenance,localTimestamp,originalMeasures,presentSum} from './activity-file-common.mjs';
const aliases={id:['id','activity id','activityid','identificador'],startedAt:['startedat','start time','starttime','datetime','fecha y hora','inicio','activity date'],date:['date','fecha','fecha local'],clock:['time of day','hora','start clock'],timezone:['timezone','time zone','zona horaria'],sport:['sport','deporte','activity type','activitytype','type','tipo'],distance:['distance','distancia','total distance','distance meters','distancemeters'],movingTime:['moving time','movingtime','movingseconds','moving seconds','tiempo en movimiento'],elapsedTime:['elapsed time','elapsedtime','elapsedseconds','elapsed seconds','tiempo transcurrido','tiempo total'],timerTime:['timer time','timertime','timerseconds','timer seconds','tiempo cronometro'],recordedTime:['duration','duration seconds','time','seconds','total time','tiempo','duracion'],avgHR:['avg hr','avghr','average heart rate','average heartrate','avg heart rate','fc media','pulsaciones medias'],maxHR:['max hr','maxhr','maximum heart rate','max heart rate','fc maxima','pulsaciones maximas'],elevation:['elevation gain','total ascent','ascent','desnivel','desnivel positivo'],temperature:['temperature','temperatura'],cadence:['cadence','avg cadence','cadencia'],power:['power','avg power','potencia'],notes:['notes','description','notas','descripcion'],lapKind:['lap kind','lapkind','tipo de vuelta','bloque'],recordKind:['record kind','recordkind','tipo de registro'],lapIndex:['lap','lap index','lap number','lapindex','vuelta'],source:['source','origen'],provider:['provider','platform','proveedor'],stravaId:['strava id','stravaid']};
const headerBase=text=>normalizedName(text).replace(/\([^)]*\)|\[[^\]]*\]/g,'').replace(/[_-]/g,' ').replace(/\s+/g,' ').trim();
export function suggestCsvMapping(headers){const result={};for(const [field,names] of Object.entries(aliases)){const found=headers.findIndex(h=>names.includes(headerBase(h))||names.includes(headerBase(h).replace(/ /g,'')));if(found>=0)result[field]=String(found);}return result;}
export function detectCsvUnits(headers,mapping,rows=[]){
 const units={distance:null,movingTime:null,elapsedTime:null,timerTime:null,recordedTime:null,elevation:'m',temperature:'c'};
 for(const field of ['distance','movingTime','elapsedTime','timerTime','recordedTime']){const index=mapping[field],head=normalizedName(headers[Number(index)]||'');if(index==null)continue;
  if(field==='distance')units.distance=/\b(?:mi|miles|millas)\b/.test(head)?'mi':/\b(?:km|kilometers|kilometros)\b/.test(head)?'km':/\b(?:m|meters|metres|metros)\b|meters$/.test(head)?'m':null;
  else units[field]=/\b(?:ms|milliseconds)\b/.test(head)?'ms':/\b(?:min|minutes|minutos)\b/.test(head)?'min':/\b(?:s|sec|seconds|segundos)\b|seconds$/.test(head)?'s':rows.slice(0,5).some(r=>String(r[Number(index)]||'').includes(':'))?'clock':null;
 }
 const elevation=normalizedName(headers[Number(mapping.elevation)]||''),temperature=normalizedName(headers[Number(mapping.temperature)]||'');if(/\b(?:ft|feet|pies)\b/.test(elevation))units.elevation='ft';if(/(?:°|\b)f\b|fahrenheit/.test(temperature))units.temperature='f';return units;
}
function csvMatrix(text,delimiter){
 const rows=[];let row=[],cell='',quoted=false,closed=false;
 const pushCell=()=>{if(row.length>=IMPORT_LIMITS.columns)throw Error('El CSV supera 80 columnas.');row.push(cell);cell='';closed=false;},pushRow=()=>{pushCell();if(row.some(v=>v.trim()))rows.push(row);row=[];if(rows.length>IMPORT_LIMITS.csvRows+1)throw Error('El CSV supera 20.000 filas.');};
 for(let i=0;i<text.length;i++){const c=text[i];if(cell.length>IMPORT_LIMITS.cellChars)throw Error('Una celda supera 20.000 caracteres.');if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;continue;}if(c==='"'){if(cell||closed)throw Error('Comillas malformadas en el CSV.');quoted=true;}else if(c===delimiter)pushCell();else if(c==='\r'||c==='\n'){if(c==='\r'&&text[i+1]==='\n')i++;pushRow();}else{if(closed&&!/\s/.test(c))throw Error('Texto después del cierre de una celda entre comillas.');if(!closed)cell+=c;}}
 if(quoted)throw Error('Una celda entre comillas no se ha cerrado.');if(cell||row.length||closed)pushRow();return rows;
}
export function inspectCsv(text,{delimiter=null}={}){
 const clean=text.replace(/^\uFEFF/,''),choices=delimiter?[delimiter]:[',',';','\t'];if(choices.some(d=>![',',';','\t'].includes(d)))throw Error('Separador CSV no permitido.');let best=null;
 for(const separator of choices){try{const matrix=csvMatrix(clean,separator),width=matrix[0]?.length||0;if(!best||width>best.headers.length)best={delimiter:separator,headers:matrix[0]||[],rows:matrix.slice(1)};}catch(error){if(delimiter)throw error;}}
 if(!best||best.headers.length<2||!best.rows.length)throw Error('CSV vacío, malformado o sin encabezados y registros.');if(best.headers.some(h=>!h.trim())||new Set(best.headers.map(h=>h.trim())).size!==best.headers.length)throw Error('Cada columna necesita un encabezado distinto y no vacío.');
 const bases=best.headers.map(headerBase);if(bases.includes('activity id')&&bases.includes('activity date')&&bases.includes('filename'))throw Error('Este esquema corresponde a una exportación de Strava. No se admite como archivo propio del dispositivo.');
 const mapping=suggestCsvMapping(best.headers);return {...best,mapping,units:detectCsvUnits(best.headers,mapping,best.rows),decimal:best.delimiter===';'?',':'.',sample:best.rows.slice(0,3)};
}
export function mapCsvActivities(document,config){
 const {mapping={},units={},timezone='Europe/Madrid',decimal='.',dateOrder='iso',ambiguity='reject',layout='activities',runningConfirmed=false}=config,csv=document.csv;
 if(!['activities','laps','mixed'].includes(layout))throw Error('Distribución del CSV no permitida.');
 const mapped=Object.entries(mapping).filter(([,v])=>v!=null&&v!=='');if(mapped.some(([field,v])=>!Object.hasOwn(aliases,field)||!/^\d+$/.test(String(v))||+v>=csv.headers.length)||new Set(mapped.map(([,v])=>String(v))).size!==mapped.length)throw Error('Revisa el mapeo: cada columna se asigna a un solo campo permitido.');
 if(mapping.distance==null||mapping.distance===''||!['startedAt','date'].some(f=>mapping[f]!=null&&mapping[f]!==''))throw Error('Asigna distancia y fecha/hora antes de preparar la vista previa.');
 if(!['movingTime','elapsedTime','timerTime','recordedTime'].some(f=>mapping[f]!=null&&mapping[f]!==''))throw Error('Asigna al menos un tiempo y su significado.');
 if((mapping.sport==null||mapping.sport==='')&&!runningConfirmed)throw Error('Asigna el deporte o confirma que todas las filas son de running.');
 if(layout!=='activities'&&(mapping.id==null||mapping.id===''))throw Error('Para agrupar vueltas necesitas una columna con identificador de actividad.');
 const records=csv.rows.map((cells,index)=>{try{
  if(cells.length!==csv.headers.length)throw Error(`La fila ${index+2} tiene ${cells.length} columnas; se esperaban ${csv.headers.length}.`);
  const get=field=>mapping[field]!=null&&mapping[field]!==''?cells[+mapping[field]]:null;
  // Inspect provenance columns even if the user leaves them unmapped.
  const provenance=Object.fromEntries(csv.headers.map((h,i)=>[headerBase(h).replace(/ /g,''),cells[i]]));assertPersonalProvenance(provenance);
  const sport=get('sport');if(sport&&!runningSport(sport))return {_importIssue:{status:'excluded',reason:`Fila ${index+2}: deporte «${sport}» excluido; solo running.`}};if(!sport&&!runningConfirmed)throw Error('Falta confirmar el deporte de esta fila.');
  const zone=get('timezone')||timezone,startValue=get('startedAt')||[get('date'),get('clock')].filter(Boolean).join('T'),time=localTimestamp(startValue,zone,{dateOrder,ambiguity});
  const distance=distanceKm(get('distance'),units.distance,decimal),moving=durationSeconds(get('movingTime'),units.movingTime,decimal),elapsed=durationSeconds(get('elapsedTime'),units.elapsedTime,decimal),timer=durationSeconds(get('timerTime'),units.timerTime,decimal),recorded=durationSeconds(get('recordedTime'),units.recordedTime,decimal),basis=moving!=null?'moving':timer!=null?'timer':recorded!=null?'recorded':'elapsed';
  const row={id:get('id')||null,startedAt:time.startedAt,date:time.date,timezone:zone,distance,seconds:moving??timer??recorded??elapsed,movingSeconds:moving,elapsedSeconds:elapsed,timerSeconds:timer,timeBasis:basis,type:'unknown',sport:'running',terrain:/treadmill|cinta|indoor/.test(normalizedName(sport))?'treadmill':'unknown',measurement:'measured',avgHR:numeric(get('avgHR'),'pulsaciones medias',{decimal}),maxHR:numeric(get('maxHR'),'pulsaciones máximas',{decimal}),elevation:numeric(get('elevation'),'desnivel',{decimal}),temperature:numeric(get('temperature'),'temperatura',{decimal}),cadence:numeric(get('cadence'),'cadencia',{decimal}),power:numeric(get('power'),'potencia',{decimal}),notes:get('notes')||'',laps:[],importWarnings:time.warning?[time.warning]:[],original:originalMeasures({distance:get('distance'),distanceUnit:units.distance,moving:get('movingTime'),elapsed:get('elapsedTime'),timer:get('timerTime'),recorded:get('recordedTime'),timeUnit:'por columna',startedAt:startValue,timezone:get('timezone'),fields:Object.fromEntries(csv.headers.map((h,i)=>[h,cells[i]]))}),_csvIndex:index,_recordKind:normalizedName(get('recordKind')||''),_lapKind:normalizedName(get('lapKind')||''),_lapIndex:get('lapIndex')};
  if(row.elevation!=null&&units.elevation==='ft')row.elevation*=.3048;if(row.temperature!=null&&units.temperature==='f')row.temperature=(row.temperature-32)*5/9;row.original.columnUnits={...units};return row;
 }catch(error){return {_csvGroup:mapping.id!=null&&mapping.id!==''?cells[+mapping.id]:null,_importIssue:{status:'invalid',reason:`Fila ${index+2}: ${error.message}`}};}});
 if(layout==='activities')return records;
 const groups=new Map(),issues=[];for(const row of records){if(row._importIssue){issues.push(row);continue;}if(!row.id){issues.push({_importIssue:{status:'invalid',reason:`Fila ${row._csvIndex+2}: falta identificador para agrupar vueltas.`}});continue;}const key=String(row.id);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}
 const badGroups=new Set(records.filter(r=>r._importIssue&&r._csvGroup).map(r=>String(r._csvGroup)));const grouped=[...groups.values()].map(rows=>{try{
  if(badGroups.has(String(rows[0].id)))throw Error('Una vuelta de este identificador contiene errores; no se importan totales parciales.');if(layout==='laps'&&new Set(rows.map(r=>r.timeBasis)).size!==1)throw Error('Las vueltas mezclan significados de tiempo; no se suman como si fueran equivalentes.');
  if(new Set(rows.map(r=>r.date)).size!==1||new Set(rows.map(r=>r.timezone)).size!==1)throw Error('Un identificador agrupa fechas o zonas distintas. Se necesita un identificador por actividad.');
  const summaries=layout==='mixed'?rows.filter(r=>['activity','summary','actividad','resumen'].includes(r._recordKind)):[],laps=layout==='mixed'?rows.filter(r=>['lap','vuelta'].includes(r._recordKind)):rows;if(layout==='mixed'&&summaries.length!==1)throw Error('Cada grupo mixto necesita exactamente una fila de resumen de actividad.');if(layout==='mixed'&&summaries.length+laps.length!==rows.length)throw Error('Confirma cada fila como actividad/resumen o vuelta.');if(!laps.length||laps.length>IMPORT_LIMITS.laps)throw Error('La actividad necesita entre 1 y 1.000 vueltas.');
  const first=summaries[0]||rows[0],activity={...first,laps:laps.map(r=>({kind:['warmup','main','work','recovery','cooldown'].includes(r._lapKind)?r._lapKind:'unknown',distance:r.distance,seconds:r.seconds,movingSeconds:r.movingSeconds,elapsedSeconds:r.elapsedSeconds,timerSeconds:r.timerSeconds,timeBasis:r.timeBasis,startedAt:r.startedAt,avgHR:r.avgHR,maxHR:r.maxHR,cadence:r.cadence,power:r.power,original:r.original,index:r._lapIndex}))};
  if(!summaries.length){activity.distance=presentSum(laps.map(l=>l.distance));activity.movingSeconds=presentSum(laps.map(l=>l.movingSeconds));activity.timerSeconds=presentSum(laps.map(l=>l.timerSeconds));activity.seconds=presentSum(laps.map(l=>l.seconds));activity.elapsedSeconds=null;activity.avgHR=null;activity.maxHR=null;activity.elevation=null;activity.importWarnings=[...activity.importWarnings,'Totales calculados sumando vueltas. Falta el resumen de actividad; no se deduce el tiempo transcurrido entre vueltas.'];activity.original={aggregation:'sum-of-laps',rows:rows.map(r=>r.original)};}
  return activity;
 }catch(error){return {_importIssue:{status:'invalid',reason:`Actividad ${rows[0].id}: ${error.message}`}};}});return [...grouped,...issues];
}
