import {recordActivity,seconds,today,uid,validateActivity} from './engine.mjs';
import {duplicateActivity} from './activity-evidence.mjs';
import {activityToday,localActivityDate,isTrainingActivity} from './activity-source.mjs';
import {known} from './profile-evidence.mjs';
import {fingerprint} from './plan-review.mjs';
import {IMPORT_LIMITS,assertPersonalProvenance,importMissing,validTimezone,distanceKm,durationSeconds,numeric,runningSport} from './activity-file-common.mjs';
import {inspectCsv,mapCsvActivities,detectCsvUnits} from './activity-csv.mjs';
export {IMPORT_LIMITS,detectCsvUnits};
const kinds=['unknown','warmup','main','work','recovery','cooldown'],types=['unknown','easy','recovery','long','walk','interval','tempo','hills','progressive','race'],optional=n=>known(n)?Number(n):null;
const safeClone=value=>value==null?null:JSON.parse(JSON.stringify(value));
const metadataFields=['original','device','samples','timerEvents','endedAt','recordedSpanSeconds','cadence','power','maxPower','calories'];
const rowList=input=>Array.isArray(input)?input:input?.activities;
export function normalizePersonalActivity(input,timezone='Europe/Madrid'){
 if(!input||typeof input!=='object'||Array.isArray(input))throw Error('El registro necesita un objeto de actividad.');assertPersonalProvenance(input);
 if(input.sport&&!runningSport(input.sport))throw Error('El deporte no es running; no se recibe.');
 if(input.type&&!types.includes(input.type))throw Error('Solo se reciben actividades de carrera o caminar; revisa el tipo.');
 if(!Array.isArray(input.laps||[])||(input.laps||[]).length>IMPORT_LIMITS.laps)throw Error('Las vueltas necesitan una lista de hasta 1.000 bloques.');if(!Array.isArray(input.samples||[])||(input.samples||[]).length>IMPORT_LIMITS.points)throw Error('Los puntos necesitan una lista de hasta 20.000 muestras.');
 const timeBasis=input.timeBasis||'moving';if(!['moving','timer','recorded','elapsed'].includes(timeBasis))throw Error('Revisa el significado del tiempo registrado.');
 const distance=numeric(input.distance,'distancia',{optional:false}),duration=known(input.seconds)?Number(input.seconds):seconds(input.time),zone=input.timezone||timezone;if(!validTimezone(zone))throw Error('La zona horaria no es válida.');const dateInfo=localActivityDate({...input,timezone:zone,dateOverride:false},timezone);
 for(const key of ['rpe','fatigue','temperature','elevation','elapsedSeconds','timerSeconds','movingSeconds','avgHR','maxHR','cadence','power','maxPower','calories'])if(input[key]!=null&&input[key]!==''&&!known(input[key]))throw Error(`El dato ${key} no es numérico; déjalo vacío si no lo sabes.`);
 const movingSeconds=timeBasis==='moving'?input.movingSeconds==null?duration:optional(input.movingSeconds):optional(input.movingSeconds);if(movingSeconds!=null&&Math.abs(movingSeconds-duration)>.001)throw Error('El tiempo en movimiento no coincide con el tiempo principal.');if(timeBasis!=='moving'&&movingSeconds!=null)throw Error('Confirma el tiempo en movimiento como tiempo principal.');
 const activity={id:input.importRecord?.key?'import-'+fingerprint(input.importRecord.key):uid(),...dateInfo,startedAt:input.startedAt||null,source:'personal-file',origin:'personal-device',dataUseConsent:true,original:safeClone(input.original),samples:safeClone(input.samples||[]),
  externalId:String(input.externalId||(!input.importRecord||input.importRecord.format==='json'?input.id:null)||input.importRecord?.key||`${input.startedAt||dateInfo.date}:${distance}:${duration}:${input.type||'unknown'}`).slice(0,200),name:String(input.name||'Actividad del archivo').slice(0,200),distance,seconds:duration,movingSeconds,elapsedSeconds:optional(input.elapsedSeconds),timerSeconds:optional(input.timerSeconds),timeBasis,
  type:types.includes(input.type)?input.type:'unknown',rpe:optional(input.rpe),fatigue:optional(input.fatigue),pain:['none','mild','relevant'].includes(input.pain)?input.pain:'unknown',feeling:['bien','normal','pesado','mal'].includes(input.feeling)?input.feeling:'unknown',performance:['better','expected','worse'].includes(input.performance)?input.performance:'unknown',terrain:['asphalt','trail','treadmill'].includes(input.terrain)?input.terrain:'unknown',temperature:optional(input.temperature),elevation:optional(input.elevation),avgHR:optional(input.avgHR),maxHR:optional(input.maxHR),measurement:['measured','estimated'].includes(input.measurement)?input.measurement:'unknown',notes:String(input.notes||'').slice(0,10000),sessionId:'',linkMode:'auto',
  laps:(input.laps||[]).map(l=>{if(!l||typeof l!=='object'||Array.isArray(l))throw Error('Cada vuelta necesita un objeto.');const distance=l.distance==null||l.distance===''?null:numeric(l.distance,'distancia de vuelta'),duration=known(l.seconds)?Number(l.seconds):l.time?seconds(l.time):null;for(const key of ['rpe','recoverySeconds','recoveryDistance','avgHR','maxHR','movingSeconds','elapsedSeconds','timerSeconds'])if(l[key]!=null&&l[key]!==''&&!known(l[key]))throw Error(`El dato ${key} de una vuelta no es numérico.`);return {id:uid(),kind:kinds.includes(l.kind)?l.kind:'unknown',distance:distance??0,seconds:duration??0,rpe:optional(l.rpe),recoverySeconds:known(l.recoverySeconds)?Number(l.recoverySeconds):l.recovery?seconds(l.recovery):0,recoveryDistance:optional(l.recoveryDistance)||0,recoveryType:['jog','walk','stop'].includes(l.recoveryType)?l.recoveryType:'jog',...Object.fromEntries(['movingSeconds','elapsedSeconds','timerSeconds','timeBasis','avgHR','maxHR','cadence','power','calories','maxSpeed','intensity','trigger','startedAt','endedAt','index','original'].filter(k=>l[k]!=null).map(k=>[k,safeClone(l[k])]))};})};
 for(const key of metadataFields)if(input[key]!=null)activity[key]=safeClone(input[key]);
 activity.importWarnings=(input.importWarnings||[]).filter(v=>typeof v==='string').slice(0,30);
 for(const l of activity.laps){if(l.distance<0||l.seconds<0||l.recoverySeconds<0||l.recoveryDistance<0||l.rpe!=null&&(l.rpe<1||l.rpe>10))throw Error('Una vuelta contiene distancia, tiempo, recuperación o esfuerzo inválidos.');for(const k of ['avgHR','maxHR'])if(l[k]!=null&&(l[k]<30||l[k]>240))throw Error('Pulsaciones de vuelta fuera del rango 30–240.');}
 for(const sample of activity.samples||[]){if(!sample||typeof sample!=='object'||Array.isArray(sample))throw Error('Cada muestra necesita un objeto.');for(const [key,val] of Object.entries(sample)){if(key==='at'){if(!Number.isFinite(Date.parse(val)))throw Error('Una muestra contiene una hora inválida.');continue;}if(!known(val))throw Error(`Muestra con ${key} no numérico.`);if(['distanceMeters','speedMps','powerWatts','cadence'].includes(key)&&+val<0||key==='latitude'&&Math.abs(+val)>90||key==='longitude'&&Math.abs(+val)>180||key==='hr'&&(+val<30||+val>240))throw Error(`Muestra con ${key} fuera de rango.`);}}
 const incomplete=activity.laps.filter(l=>!(l.seconds>0)||!(l.distance>0)&&l.kind==='unknown');
 if(incomplete.length){activity.originalLaps=safeClone(input.laps);activity.laps=activity.laps.filter(l=>l.seconds>0&&(l.distance>0||l.kind!=='unknown'));activity.importWarnings.push(`${incomplete.length} vuelta(s) incompleta(s) conservadas como datos originales; no se usan como bloques medidos.`);}
 if(activity.timeBasis==='moving'&&activity.laps.some(l=>l.timeBasis&&l.timeBasis!=='moving')){activity.originalLaps=safeClone(input.laps);activity.laps=[];activity.importWarnings.push('Las vueltas no incluyen tiempo en movimiento comparable. Se conservan como originales y no se comparan con bloques rápidos.');}
 if(input.importRecord){activity.importSources=[{...safeClone(input.importRecord),source:'personal-file',origin:'personal-device',dataUseConsent:true,original:safeClone(input.original),notes:activity.notes}];}
 const errors=validateActivity(activity,activityToday(activity.timezone));if(errors.length)throw Error(errors.join(' '));return activity;
}
export async function parseActivityFile(file,options={}){
 const bytes=typeof file.data==='string'?new TextEncoder().encode(file.data):file.data instanceof ArrayBuffer?new Uint8Array(file.data):file.data;
 if(!(bytes instanceof Uint8Array)||!bytes.length)throw Error('El archivo está vacío o no contiene bytes válidos.');if(bytes.length>IMPORT_LIMITS.fileBytes)throw Error('El archivo supera 10 MB.');
 const hash=Array.from(new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join(''),name=String(file.name||'archivo').slice(0,200),isFit=bytes.length>=12&&new TextDecoder().decode(bytes.slice(8,12))==='.FIT';
 if(bytes[0]===0x50&&bytes[1]===0x4b)throw Error('Los archivos ZIP no se importan directamente; extrae el TCX, CSV, FIT o JSON.');
 let text=null;try{if(!isFit)text=new TextDecoder('utf-8',{fatal:true}).decode(bytes).replace(/^\uFEFF/,'').trim();}catch{throw Error('Texto no válido en UTF-8. Exporta el CSV o TCX como UTF-8.');}
 const format=isFit?'fit':text?.startsWith('<')?'tcx':text?.startsWith('{')||text?.startsWith('[')?'json':/\.fit$/i.test(name)?'fit':/\.tcx$/i.test(name)?'tcx':/\.csv$/i.test(name)||text?.includes('\n')?'csv':'unknown';
 const document={name,format,hash,byteLength:bytes.length,activities:[],units:{distance:'m',time:'s'},configuration:{timezone:options.timezone||'Europe/Madrid',confirmed:false},requiresMapping:format==='csv'};
 if(format==='fit'){const {parseFit}=await import('./activity-fit.mjs');document.activities=parseFit(bytes,document.configuration);}
 else if(format==='tcx'){const {parseTcx}=await import('./activity-tcx.mjs');document.activities=parseTcx(text,document.configuration);}
 else if(format==='json'){let raw;try{raw=JSON.parse(text);}catch{throw Error('JSON malformado.');}assertPersonalProvenance(raw);const rows=rowList(raw);if(!Array.isArray(rows)||!rows.length||rows.length>IMPORT_LIMITS.activities)throw Error('El JSON necesita una lista de 1 a 500 actividades.');document.json=rows;document.units={distance:'km',time:'s'};document.activities=rows;}
 else if(format==='csv'){document.csv=inspectCsv(text,{delimiter:options.delimiter});document.configuration={...document.configuration,mapping:document.csv.mapping,units:document.csv.units,decimal:document.csv.decimal,dateOrder:'iso',ambiguity:'reject',layout:'activities',runningConfirmed:false};document.units=document.csv.units;}
 else throw Error('Formato no reconocido. Usa TCX de actividades, CSV con encabezados, FIT de actividad o el JSON de Zancada.');
 return attachRecords(document);
}
function attachRecords(document){if(document.activities.reduce((n,row)=>n+(Array.isArray(row?.samples)?row.samples.length:0),0)>IMPORT_LIMITS.points)throw Error('El archivo supera 20.000 puntos entre sus actividades.');return {...document,activities:document.activities.map((row,index)=>row?._importIssue?row:{...row,importRecord:{key:`${document.hash}:${index}`,fileHash:document.hash,fileName:document.name,format:document.format,index,recordId:String(row?.id||row?.externalId||index),units:safeClone(document.units),timezoneConfirmed:document.configuration.timezone,confirmed:document.configuration.confirmed===true}})};}
export function configureActivityFile(document,configuration){
 const config={...document.configuration,...configuration};if(!validTimezone(config.timezone))throw Error('Confirma una zona horaria válida.');let activities=document.activities,units=document.units;
 if(document.format==='csv'){activities=mapCsvActivities(document,config);units=config.units;}
 else if(document.format==='json'){units={...document.units,...config.units};activities=document.json.map(row=>{try{const distance=distanceKm(row.distance,units.distance),secondsValue=row.seconds!=null?durationSeconds(row.seconds,units.time):seconds(row.time),original=row.original||{distance:{value:row.distance,unit:units.distance},times:{[row.timeBasis||'moving']:{value:row.seconds??row.time,unit:row.seconds!=null?units.time:'clock'},elapsed:{value:row.elapsedSeconds??(row.timeBasis==="elapsed"?row.seconds??row.time:null),unit:units.time},timer:{value:row.timerSeconds??(row.timeBasis==="timer"?row.seconds??row.time:null),unit:units.time}},startedAt:row.startedAt||null,timezone:row.timezone||null};return {...row,distance,seconds:secondsValue,elapsedSeconds:row.elapsedSeconds!=null?durationSeconds(row.elapsedSeconds,units.time):null,timerSeconds:row.timerSeconds!=null?durationSeconds(row.timerSeconds,units.time):null,movingSeconds:row.movingSeconds!=null?durationSeconds(row.movingSeconds,units.time):undefined,timezone:row.timezone||config.timezone,original,laps:(row.laps||[]).map(l=>({...l,distance:l.distance!=null?distanceKm(l.distance,units.distance):null,seconds:l.seconds!=null?durationSeconds(l.seconds,units.time):seconds(l.time),recoveryDistance:l.recoveryDistance!=null?distanceKm(l.recoveryDistance,units.distance):0,recoverySeconds:l.recoverySeconds!=null?durationSeconds(l.recoverySeconds,units.time):l.recovery?seconds(l.recovery):0,original:l}))};}catch(error){return {_importIssue:{status:'invalid',reason:error.message}};}});}
 else activities=document.activities.map(row=>({...row,timezone:config.timezone}));
 return attachRecords({...document,configuration:config,units,activities,requiresMapping:false});
}
export function combineActivityFiles(documents){
 if(!Array.isArray(documents)||!documents.length||documents.length>IMPORT_LIMITS.files)throw Error('Selecciona entre 1 y 10 archivos.');if(documents.reduce((n,d)=>n+d.byteLength,0)>IMPORT_LIMITS.batchBytes)throw Error('El conjunto supera 30 MB.');if(documents.some(d=>d.requiresMapping))throw Error('Completa el mapeo CSV antes de preparar las actividades.');const activities=documents.flatMap(d=>d.activities);if(!activities.length||activities.length>IMPORT_LIMITS.activities)throw Error('Se admiten entre 1 y 500 actividades por importación.');return {activities,files:documents.map(d=>({name:d.name,hash:d.hash,format:d.format})),requiresConfirmation:true,confirmed:documents.every(d=>d.configuration.confirmed)};
}
export function previewActivityImport(state,input){
 const rows=rowList(input);if(!Array.isArray(rows)||!rows.length||rows.length>IMPORT_LIMITS.activities)throw Error('El archivo debe contener una lista de 1 a 500 actividades.');const seen=[...(state.activities||[]).filter(isTrainingActivity)];
 return rows.map((row,index)=>{const empty={index,activity:null,missing:[],warnings:[],duplicateId:null,exact:false,reason:null,fileName:row?.importRecord?.fileName||null};if(row?.sport&&!runningSport(row.sport))return {...empty,status:'excluded',reason:'Deporte «'+String(row.sport).slice(0,100)+'» excluido; solo running.'};if(row?._importIssue)return {...empty,status:row._importIssue.status==='excluded'?'excluded':'invalid',reason:String(row._importIssue.reason).slice(0,1000)};try{const activity=normalizePersonalActivity(row,state.profile?.timezone||'Europe/Madrid'),duplicate=duplicateActivity({...activity,id:`preview-${index}`},seen),missing=importMissing(activity),warnings=activity.importWarnings||[],base={...empty,activity,missing,warnings};if(duplicate)return {...base,status:'duplicate',reason:duplicate.reason,duplicateId:duplicate.id,exact:duplicate.exact};seen.push(activity);return {...base,status:'ready'};}catch(error){return {...empty,status:'invalid',reason:error.message};}});
}
function linkImportedEvidence(state,row,decision){
 const before=state.activities.find(a=>a.id===decision.targetId&&isTrainingActivity(a));if(!before)throw Error('El registro elegido ya no está disponible. Revisa los duplicados.');const candidate=duplicateActivity({...row.activity,id:'link-check'},[before]);if(!candidate)throw Error('El archivo y el registro elegido no son una coincidencia comprobable. Revisa fecha, hora, distancia y tiempos.');
 const incoming=row.activity.importSources?.length?row.activity.importSources:[{key:row.activity.externalId,fileName:null,format:'json',recordId:row.activity.externalId,source:'personal-file',origin:'personal-device',dataUseConsent:true,original:{distance:{value:row.activity.distance,unit:'km'},times:{[row.activity.timeBasis||'moving']:{value:row.activity.seconds,unit:'s'}},startedAt:row.activity.startedAt},notes:row.activity.notes}],existing=before.importSources||[],fresh=incoming.filter(s=>!existing.some(old=>old.key===s.key));
 if(!fresh.length)return {state,linked:false};const evidence=safeClone(Object.fromEntries(['distance','seconds','movingSeconds','elapsedSeconds','timerSeconds','timeBasis','startedAt','timezone','avgHR','maxHR','laps','originalLaps','samples','timerEvents','device','cadence','power','temperature','elevation'].filter(k=>row.activity[k]!=null).map(k=>[k,row.activity[k]]))),copy={...before,importSources:[...existing,...fresh.map(source=>({...source,evidence}))]};if(decision.fillMissing){for(const key of ['avgHR','maxHR','elapsedSeconds','timerSeconds','cadence','power','maxPower','temperature','elevation','endedAt','recordedSpanSeconds'])if((copy[key]==null||copy[key]==='')&&row.activity[key]!=null)copy[key]=safeClone(row.activity[key]);if(!copy.startedAt&&row.activity.startedAt&&localActivityDate({...row.activity,timezone:copy.timezone||state.profile?.timezone}).date===copy.date)copy.startedAt=row.activity.startedAt;if(!copy.laps?.length&&row.activity.laps.length)copy.laps=safeClone(row.activity.laps);if(!copy.samples?.length&&row.activity.samples?.length)copy.samples=safeClone(row.activity.samples);if(!copy.originalLaps&&row.activity.originalLaps)copy.originalLaps=safeClone(row.activity.originalLaps);}
 const errors=validateActivity(copy,activityToday(copy.timezone||state.profile?.timezone));if(errors.length)throw Error('No se puede completar ese registro sin alterar sus medidas: '+errors.join(' '));
 const next={...state,activities:state.activities.map(a=>a.id===before.id?copy:a),proposals:(state.proposals||[]).map(v=>v.status==='pending'&&(v.activityId===before.id||(v.evidenceIds||[]).includes(before.id))?{...v,status:'superseded',supersededReason:'Se ha vinculado evidencia original de un dispositivo; revisa el análisis actualizado.'}:v),changes:[{id:uid(),date:new Date().toISOString(),type:'Archivo vinculado a una carrera',reason:'Se conserva el identificador, medidas principales, notas y asociación de la carrera. La evidencia del archivo se guarda por separado; el calendario conserva su prescripción.',beforeActivity:before,afterActivity:copy},...(state.changes||[])]};return {state:next,linked:true};
}
/** @param {{consent?:boolean,selectedIndices?:number[]|null,duplicateDecisions?:{index:number,action:string,targetId?:string,fillMissing?:boolean}[]}} options */
export function receivePersonalActivities(state,input,options={}){
 const {consent=false,selectedIndices=null,duplicateDecisions=[]}=options;if(!consent)throw Error('Confirma que son archivos propios autorizados para el seguimiento.');if(input?.requiresConfirmation&&!input.confirmed)throw Error('Confirma unidades, zona horaria y mapeo antes de guardar.');
 if(selectedIndices!=null&&(!Array.isArray(selectedIndices)||selectedIndices.some(i=>!Number.isInteger(i)||i<0)))throw Error('Selección de actividades no válida.');if(!Array.isArray(duplicateDecisions)||duplicateDecisions.length>IMPORT_LIMITS.activities||new Set(duplicateDecisions.map(d=>d.index)).size!==duplicateDecisions.length||duplicateDecisions.some(d=>!d||!Number.isInteger(d.index)||!['skip','link','separate'].includes(d.action)||Object.keys(d).some(k=>!['index','action','targetId','fillMissing'].includes(k))))throw Error('Revisa la decisión de cada duplicado.');
 const preview=previewActivityImport(state,input);if(selectedIndices?.some(i=>i>=preview.length)||duplicateDecisions.some(d=>d.index<0||d.index>=preview.length||preview[d.index].status!=='duplicate'))throw Error('La selección o sus duplicados han cambiado. Vuelve a preparar la vista previa.');let next=state;const received=[],linked=[];
 for(const row of preview){const decision=duplicateDecisions.find(d=>d.index===row.index);if(row.status==='duplicate'){if(!decision||decision.action==='skip')continue;if(decision.action==='link'){const result=linkImportedEvidence(next,row,{...decision,targetId:decision.targetId||row.duplicateId});next=result.state;if(result.linked)linked.push(decision.targetId||row.duplicateId);continue;}if(row.exact)throw Error('Una copia exacta no puede guardarse como otra carrera. Vincúlala o ignórala.');const result=recordActivity(next,{...row.activity,duplicateConfirmed:true,linkMode:'none'});next=result.state;received.push(result.activity.id);continue;}
  if(row.status!=='ready'||selectedIndices&&!selectedIndices.includes(row.index))continue;const result=recordActivity(next,row.activity);next=result.state;received.push(result.activity.id);
 }
 if(received.length)next={...next,changes:[{id:uid(),date:new Date().toISOString(),type:'Actividades propias recibidas',reason:`${received.length} actividades autorizadas guardadas en sus fechas locales; el calendario conserva su prescripción y cualquier ajuste requiere revisión.`,receivedActivityIds:received},...next.changes]};
 if(new TextEncoder().encode(JSON.stringify(next)).length>IMPORT_LIMITS.persistedBytes)throw Error('Estos datos superarían 1,8 MB de almacenamiento personal. Importa un archivo más corto; no se ha guardado parcialmente.');
 return {state:next,received,linked,duplicates:preview.filter(r=>r.status==='duplicate').length,invalid:preview.filter(r=>r.status==='invalid').length,excluded:preview.filter(r=>r.status==='excluded').length,preview,date:today()};
}
