import {Decoder,Stream} from '@garmin/fitsdk';
import {IMPORT_LIMITS,assertPersonalProvenance,originalMeasures,numeric} from './activity-file-common.mjs';
const iso=value=>value instanceof Date?value.toISOString():typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;
const measure=(v,name)=>numeric(v,name);
const extractTime=message=>({movingSeconds:measure(message.totalMovingTime,'tiempo en movimiento'),timerSeconds:measure(message.totalTimerTime,'tiempo de cronómetro'),elapsedSeconds:measure(message.totalElapsedTime,'tiempo transcurrido')});
const timeBasis=value=>value.movingSeconds!=null?'moving':value.timerSeconds!=null?'timer':'elapsed';
const timedSeconds=value=>value.movingSeconds??value.timerSeconds??value.elapsedSeconds;
export function parseFit(bytes,{timezone='Europe/Madrid'}={}){
 if(bytes.length<14||![12,14].includes(bytes[0]))throw Error('Cabecera FIT incompleta o no compatible.');const declared=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(4,true);if(bytes[0]+declared+2!==bytes.length)throw Error('FIT truncado o con bytes adicionales; el tamaño no coincide con su cabecera.');
 const stream=Stream.fromArrayBuffer(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)),decoder=new Decoder(stream);
 if(!decoder.isFIT())throw Error('El archivo no contiene una cabecera FIT válida.');if(!decoder.checkIntegrity())throw Error('FIT truncado o alterado: no supera la comprobación de tamaño y CRC.');
 let count=0;const {messages,errors}=decoder.read({applyScaleAndOffset:true,convertTypesToStrings:true,convertDateTimesToDates:true,mesgListener:()=>{if(++count>IMPORT_LIMITS.points+IMPORT_LIMITS.activities+IMPORT_LIMITS.laps*2)throw Error('El FIT contiene demasiados mensajes.');}});
 if(errors.length)throw Error('No se puede decodificar el FIT íntegro: '+String(errors[0]?.message||errors[0]).slice(0,200));assertPersonalProvenance(messages);
 if(messages.fileIdMesgs?.some(m=>m.type!=='activity'))throw Error('Solo se admiten archivos FIT de actividad; un entrenamiento o trayecto no es una carrera realizada.');
 const sessions=messages.sessionMesgs||[];if(!sessions.length||sessions.length>IMPORT_LIMITS.activities)throw Error('El FIT necesita entre 1 y 500 resúmenes de sesión; no se inventan sesiones a partir de puntos.');
 const records=messages.recordMesgs||[],allLaps=messages.lapMesgs||[];if(records.length>IMPORT_LIMITS.points)throw Error('El FIT supera 20.000 puntos.');
 return sessions.map((s,index)=>{try{
  if(s.sport!=='running')return {_importIssue:{status:'excluded',reason:`Sesión FIT ${index+1}: deporte «${s.sport||'sin confirmar'}» excluido; solo running.`}};
  const start=iso(s.startTime),end=iso(s.timestamp);if(!start||!end)throw Error('Falta fecha de inicio o fin de sesión.');if(end<start)throw Error('El fin de sesión precede al inicio.');
  const contains=m=>{const at=iso(m.timestamp);return at&&at>=start&&at<=end;},lapMessages=Number.isInteger(s.firstLapIndex)&&Number.isInteger(s.numLaps)?allLaps.slice(s.firstLapIndex,s.firstLapIndex+s.numLaps):allLaps.filter(l=>{const lapStart=iso(l.startTime);return lapStart&&lapStart>=start&&contains(l);});if(lapMessages.length>IMPORT_LIMITS.laps)throw Error('La sesión supera 1.000 vueltas.');
  if(Number.isInteger(s.numLaps)&&lapMessages.length!==s.numLaps)throw Error('Las vueltas declaradas no coinciden con las disponibles.');
  const metrics=m=>({avgHR:measure(m.avgHeartRate,'pulsaciones medias'),maxHR:measure(m.maxHeartRate,'pulsaciones máximas'),cadence:measure(m.avgCadence,'cadencia'),power:measure(m.avgPower,'potencia'),maxPower:measure(m.maxPower,'potencia máxima'),elevation:measure(m.totalAscent,'desnivel'),calories:measure(m.totalCalories,'calorías'),temperature:measure(m.avgTemperature,'temperatura')});
  const laps=lapMessages.map((lap,i)=>{const time=extractTime(lap),meters=measure(lap.totalDistance,'distancia de vuelta');return {index:i+1,kind:'unknown',distance:meters==null?null:meters/1000,seconds:timedSeconds(time),...time,timeBasis:timeBasis(time),startedAt:iso(lap.startTime),endedAt:iso(lap.timestamp),...metrics(lap),intensity:lap.intensity||null,trigger:lap.lapTrigger||null,original:originalMeasures({distance:lap.totalDistance,distanceUnit:'m',moving:lap.totalMovingTime,timer:lap.totalTimerTime,elapsed:lap.totalElapsedTime,startedAt:iso(lap.startTime),fields:{messageIndex:lap.messageIndex,intensity:lap.intensity,lapTrigger:lap.lapTrigger}})};});
  const samples=records.filter(contains).map(r=>{const result={at:iso(r.timestamp),distanceMeters:r.distance,hr:r.heartRate,cadence:r.cadence,altitudeMeters:r.enhancedAltitude??r.altitude,speedMps:r.enhancedSpeed??r.speed,powerWatts:r.power,temperature:r.temperature,latitude:r.positionLat!=null?r.positionLat*180/2147483648:null,longitude:r.positionLong!=null?r.positionLong*180/2147483648:null};return Object.fromEntries(Object.entries(result).filter(([,v])=>v!=null));}),time=extractTime(s),meters=measure(s.totalDistance,'distancia'),warnings=['El tiempo de cronómetro FIT no se identifica automáticamente con tiempo en movimiento.','Las vueltas conservan su intensidad y disparador; su papel de trabajo o recuperación requiere confirmación.'];
  const local=messages.activityMesgs?.find(a=>a.localTimestamp&&iso(a.timestamp)===end),localTime=local?.localTimestamp;const reportedLocal=localTime instanceof Date?localTime.toISOString():typeof localTime==='number'?new Date(localTime*1000+631065600000).toISOString():null;
  return {id:`${messages.fileIdMesgs?.[0]?.serialNumber??'device'}:${start}:${index}`,startedAt:start,endedAt:end,timezone,sport:'running',type:'unknown',terrain:s.subSport==='treadmill'?'treadmill':s.subSport==='trail'?'trail':'unknown',distance:meters==null?null:meters/1000,seconds:timedSeconds(time),...time,timeBasis:timeBasis(time),...metrics(s),laps,samples,measurement:'measured',recordedSpanSeconds:(Date.parse(end)-Date.parse(start))/1000,importWarnings:warnings,original:originalMeasures({distance:s.totalDistance,distanceUnit:'m',moving:s.totalMovingTime,timer:s.totalTimerTime,elapsed:s.totalElapsedTime,startedAt:start,timezone:null,fields:{sport:s.sport,subSport:s.subSport,firstLapIndex:s.firstLapIndex,numLaps:s.numLaps,manufacturer:messages.fileIdMesgs?.[0]?.manufacturer,recordedLocalTimestamp:reportedLocal}}),device:{manufacturer:messages.fileIdMesgs?.[0]?.manufacturer||null,product:messages.fileIdMesgs?.[0]?.product||null},timerEvents:(messages.eventMesgs||[]).filter(e=>e.event==='timer'&&contains(e)).map(e=>({at:iso(e.timestamp),eventType:e.eventType}))};
 }catch(error){return {_importIssue:{status:'invalid',reason:`Sesión FIT ${index+1}: ${error.message}`}};}});
}
