import {XMLParser,XMLValidator} from 'fast-xml-parser';
import {IMPORT_LIMITS,numeric,presentSum,originalMeasures,runningSport,assertPersonalProvenance,localTimestamp} from './activity-file-common.mjs';
const list=value=>value==null?[]:Array.isArray(value)?value:[value];
const value=node=>node&&typeof node==='object'?node['#text']??value(node.Value):node;
const number=(node,label)=>numeric(value(node),label);
const hr=node=>number(node?.Value,'pulsaciones');
function extension(node,name){if(!node||typeof node!=='object')return null;if(Object.hasOwn(node,name))return value(node[name]);for(const child of Object.values(node)){if(child&&typeof child==='object'){const found=extension(child,name);if(found!=null)return found;}}return null;}
function xmlDepth(text){let depth=0;for(const match of text.matchAll(/<!--[\s\S]*?-->|<!\[CDATA\[[\s\S]*?\]\]>|<\?[\s\S]*?\?>|<\/?[\w:](?:[^>"']|"[^"]*"|'[^']*')*>/g)){const tag=match[0];if(tag.startsWith('<!')||tag.startsWith('<?'))continue;if(tag.startsWith('</'))depth--;else if(!tag.endsWith('/>'))depth++;if(depth>IMPORT_LIMITS.depth)throw Error('El TCX está demasiado anidado.');}}
export function parseTcx(text,{timezone='Europe/Madrid'}={}){
 if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('El TCX contiene DTD o entidades externas; no se admite.');xmlDepth(text);
 const valid=XMLValidator.validate(text);if(valid!==true)throw Error(`TCX malformado: ${valid.err.msg} (línea ${valid.err.line}).`);
 const parser=new XMLParser({ignoreAttributes:false,removeNSPrefix:true,parseTagValue:false,parseAttributeValue:false,processEntities:false,ignoreDeclaration:true,isArray:name=>['Activity','Lap','Track','Trackpoint'].includes(name)}),tree=parser.parse(text),root=tree.TrainingCenterDatabase;
 if(!root||typeof root!=='object')throw Error('Falta TrainingCenterDatabase: este XML no es un archivo TCX de actividades.');
 if(/strava/i.test(String(value(root.Author?.Name)||'')))throw Error('El autor del TCX es Strava. No se admite como archivo propio del dispositivo.');assertPersonalProvenance(root);
 const activities=list(root.Activities?.Activity);if(!activities.length||activities.length>IMPORT_LIMITS.activities)throw Error('El TCX necesita entre 1 y 500 actividades.');let count=0;
 return activities.map((activity,index)=>{try{
  const sport=activity['@_Sport'];if(!runningSport(sport))return {_importIssue:{status:'excluded',reason:`Actividad ${index+1}: deporte «${sport||'sin confirmar'}» excluido; el TCX debe identificar Running.`}};
  if(/strava/i.test(String(value(activity.Creator?.Name)||'')))throw Error('El creador declara origen Strava.');
  const rawLaps=list(activity.Lap);if(!rawLaps.length||rawLaps.length>IMPORT_LIMITS.laps)throw Error('El TCX necesita entre 1 y 1.000 vueltas por actividad.');
  const samples=[],laps=rawLaps.map((lap,i)=>{
   const trackpoints=list(lap.Track).flatMap(track=>list(track.Trackpoint));count+=trackpoints.length;if(count>IMPORT_LIMITS.points)throw Error('El TCX supera 20.000 puntos; utiliza un archivo más corto.');
   const points=trackpoints.map(point=>{const result={at:value(point.Time)||null,distanceMeters:number(point.DistanceMeters,'distancia acumulada'),altitudeMeters:number(point.AltitudeMeters,'altitud'),hr:hr(point.HeartRateBpm),cadence:number(point.Cadence??extension(point.Extensions,'RunCadence'),'cadencia'),speedMps:number(extension(point.Extensions,'Speed'),'velocidad'),powerWatts:number(extension(point.Extensions,'Watts'),'potencia'),temperature:number(extension(point.Extensions,'Temperature'),'temperatura'),latitude:number(point.Position?.LatitudeDegrees,'latitud'),longitude:number(point.Position?.LongitudeDegrees,'longitud')};if(result.at)localTimestamp(result.at,timezone);return Object.fromEntries(Object.entries(result).filter(([,v])=>v!=null));});samples.push(...points);
   const meters=number(lap.DistanceMeters,'distancia de vuelta'),recorded=number(lap.TotalTimeSeconds,'tiempo registrado de vuelta'),moving=number(extension(lap.Extensions,'MovingTimeSeconds'),'tiempo en movimiento'),elapsed=number(extension(lap.Extensions,'TotalElapsedTimeSeconds'),'tiempo transcurrido'),timer=number(extension(lap.Extensions,'TotalTimerTimeSeconds'),'tiempo de cronómetro');
   return {index:i+1,kind:'unknown',distance:meters==null?null:meters/1000,seconds:moving??timer??recorded??elapsed,movingSeconds:moving,elapsedSeconds:elapsed,timerSeconds:timer,timeBasis:moving!=null?'moving':timer!=null?'timer':recorded!=null?'recorded':'elapsed',startedAt:lap['@_StartTime']||null,avgHR:hr(lap.AverageHeartRateBpm),maxHR:hr(lap.MaximumHeartRateBpm),cadence:number(lap.Cadence,'cadencia'),calories:number(lap.Calories,'calorías'),maxSpeed:number(lap.MaximumSpeed,'velocidad máxima'),intensity:value(lap.Intensity)||null,trigger:value(lap.TriggerMethod)||null,original:originalMeasures({distance:value(lap.DistanceMeters),distanceUnit:'m',moving:extension(lap.Extensions,'MovingTimeSeconds'),elapsed:extension(lap.Extensions,'TotalElapsedTimeSeconds'),timer:extension(lap.Extensions,'TotalTimerTimeSeconds'),recorded:value(lap.TotalTimeSeconds),startedAt:lap['@_StartTime'],fields:{AverageHeartRateBpm:value(lap.AverageHeartRateBpm?.Value),MaximumHeartRateBpm:value(lap.MaximumHeartRateBpm?.Value),Intensity:value(lap.Intensity),TriggerMethod:value(lap.TriggerMethod)}})};
  });
  const startValue=value(activity.Id)||rawLaps[0]['@_StartTime'],time=localTimestamp(startValue,timezone),distance=presentSum(laps.map(l=>l.distance)),moving=presentSum(laps.map(l=>l.movingSeconds)),timer=presentSum(laps.map(l=>l.timerSeconds)),recorded=presentSum(rawLaps.map(l=>number(l.TotalTimeSeconds,'tiempo registrado'))),explicitMoving=number(extension(activity.Extensions,'MovingTimeSeconds'),'tiempo en movimiento'),explicitElapsed=number(extension(activity.Extensions,'TotalElapsedTimeSeconds'),'tiempo transcurrido'),explicitTimer=number(extension(activity.Extensions,'TotalTimerTimeSeconds'),'cronómetro'),warnings=['TCX TotalTimeSeconds se conserva como tiempo registrado; no acredita tiempo en movimiento.','Las vueltas no indican por sí solas trabajo o recuperación; confirma su papel si necesitas comparar intervalos.'];
  if(time.warning)warnings.push(time.warning);const movingSeconds=explicitMoving??moving,timerSeconds=explicitTimer??timer,elapsedSeconds=explicitElapsed,timeBasis=movingSeconds!=null?'moving':timerSeconds!=null?'timer':recorded!=null?'recorded':'elapsed';
  const summaryHR=list(activity.Extensions).map(e=>extension(e,'AverageHeartRateBpm')).find(v=>v!=null),summaryMax=extension(activity.Extensions,'MaximumHeartRateBpm'),first=Date.parse(startValue),last=Math.max(...samples.map(p=>Date.parse(p.at)).filter(Number.isFinite));
  // Keep sensor values and lap summaries; do not invent a session average from sparse samples.
  return {id:startValue,startedAt:time.startedAt,date:time.date,timezone,sport:'running',type:'unknown',terrain:/treadmill|cinta/i.test(String(extension(activity.Extensions,'SubSport')||''))?'treadmill':'unknown',distance,seconds:movingSeconds??timerSeconds??recorded??elapsedSeconds,movingSeconds,timerSeconds,elapsedSeconds,timeBasis,avgHR:summaryHR!=null?numeric(summaryHR,'pulsaciones medias'):laps.length===1?laps[0].avgHR:null,maxHR:summaryMax!=null?numeric(summaryMax,'pulsaciones máximas'):laps.length===1?laps[0].maxHR:null,elevation:number(extension(activity.Extensions,'TotalAscent'),'desnivel positivo'),calories:presentSum(laps.map(l=>l.calories)),cadence:number(extension(activity.Extensions,'AvgRunCadence'),'cadencia'),notes:String(value(activity.Notes)||''),measurement:'measured',laps,samples,recordedSpanSeconds:Number.isFinite(first)&&Number.isFinite(last)?(last-first)/1000:null,importWarnings:warnings,original:{format:'tcx',id:startValue,sport,distance:{value:presentSum(rawLaps.map(l=>number(l.DistanceMeters,'distancia'))),unit:'m',aggregation:'sum-of-laps'},times:{recorded:{value:recorded,unit:'s',aggregation:'sum-of-laps'},moving:{value:explicitMoving,unit:'s'},elapsed:{value:explicitElapsed,unit:'s'},timer:{value:explicitTimer,unit:'s'}},startedAt:startValue,timezone:null,creator:activity.Creator?.Name||root.Author?.Name||null}};
 }catch(error){return {_importIssue:{status:'invalid',reason:`Actividad TCX ${index+1}: ${error.message}`}};}});
}
