import {CACHE_SECONDS,randomSecret,digest,seal,open,scopeList,canReadActivities,allowedRun,normalizeRun,ProviderError,rotateTokens,safeError} from './strava-core.mjs';
const now=()=>Math.floor(Date.now()/1000);
const defaults={days:90,includeTrail:true,includeTreadmill:true,includePrivate:false};
export function cleanSettings(s={}){return {days:[30,90,180,365].includes(+s.days)?+s.days:90,includeTrail:s.includeTrail!==false,includeTreadmill:s.includeTreadmill!==false,includePrivate:s.includePrivate===true};}
export class StravaService{
 constructor(db,config,fetcher=fetch){this.db=db;this.config=config;this.fetcher=fetcher;}
 q(sql,...args){return this.db.prepare(sql).bind(...args);}
 async connection(user){return this.q('SELECT * FROM strava_connection WHERE user_id = ?',user).first();}
 async settings(user){const row=await this.q('SELECT data FROM strava_settings WHERE user_id = ?',user).first();return row?JSON.parse(row.data):defaults;}
 async setSettings(user,settings){const clean=cleanSettings(settings);await this.q('INSERT INTO strava_settings (user_id,data) VALUES (?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data',user,JSON.stringify(clean)).run();return clean;}
 configured(){return Boolean(this.config.STRAVA_TOKEN_KEY&&this.config.STRAVA_CLIENT_ID&&this.config.STRAVA_CLIENT_SECRET&&this.config.STRAVA_REDIRECT_URI);}
 async purge(){const t=now();await this.db.batch([this.q('DELETE FROM strava_cache WHERE expires_at <= ?',t),this.q('DELETE FROM strava_oauth WHERE expires_at <= ?',t),this.q('DELETE FROM strava_jobs WHERE created < ?',t-CACHE_SECONDS)]);}
 async status(user){await this.purge();const c=await this.connection(user),pending=await this.q('SELECT COUNT(*) AS n FROM strava_jobs WHERE user_id=? AND attempts < 8',user).first();let state=c?.status||'disconnected';if(c&&state==='connected'&&pending.n)state='syncing';if(c&&state==='connected'){const tokens=await open(c.cipher,this.config.STRAVA_TOKEN_KEY,user);if(tokens.expiresAt&&tokens.expiresAt<=now()&&!tokens.refreshToken)state='authorization_expired';}
 const data=await this.q('SELECT c.id,c.data,c.expires_at,n.data AS notes FROM strava_cache c LEFT JOIN strava_notes n ON n.id=c.id AND n.user_id=c.user_id WHERE c.user_id=? AND c.expires_at>?',user,now()).all();
 const notes=await this.q('SELECT n.id,n.data FROM strava_notes n LEFT JOIN strava_cache c ON c.id=n.id AND c.user_id=n.user_id WHERE n.user_id=? AND c.id IS NULL',user).all();
 return {configured:this.configured(),tokenConfigured:Boolean(this.config.STRAVA_TOKEN_KEY),retentionConfigured:this.config.STRAVA_RETENTION_JOB_ENABLED==='true',state,account:c?`Atleta ${c.athlete_id}`:null,mode:c?.mode||null,scopes:c?JSON.parse(c.scopes):[],privateAccess:c?.mode==='token'?'unverified':c?JSON.parse(c.scopes).includes('activity:read_all'):false,lastVerified:c?.verified_at||null,lastSync:c?.last_sync||null,pending:pending?.n||0,settings:await this.settings(user),activities:data.results.map(row=>({id:row.id,...JSON.parse(row.data),expiresAt:row.expires_at,notes:row.notes?JSON.parse(row.notes):null})).sort((a,b)=>b.date.localeCompare(a.date)||b.localTime.localeCompare(a.localTime)),orphanNotes:notes.results.map(n=>({id:n.id,...JSON.parse(n.data)})),policy:{analysis:false,retentionDays:7,reviewed:'2026-10-01',reason:'La política de la API de Strava en vigor desde el 1 de junio de 2026 prohíbe procesar sus datos para análisis (5.4), usarlos con IA (5.3), combinarlos con otros datos y conservarlos más de siete días (6.2). Estas actividades se muestran solo a ti y separadas del motor del plan.'},checklist:this.checklist(),backgroundConfigured:Boolean(this.config.STRAVA_WEBHOOK_SUBSCRIPTION_ID&&this.config.STRAVA_WEBHOOK_PATH_SECRET),backgroundVerified:false};
 }
 // Real server configuration, without exposing any value.
 checklist(){const c=this.config;return [{id:'app',label:'Aplicación registrada en Strava (STRAVA_CLIENT_ID y STRAVA_CLIENT_SECRET)',done:Boolean(c.STRAVA_CLIENT_ID&&c.STRAVA_CLIENT_SECRET)},{id:'redirect',label:'Dirección de retorno OAuth (STRAVA_REDIRECT_URI)',done:Boolean(c.STRAVA_REDIRECT_URI)},{id:'key',label:'Clave de cifrado de tokens (STRAVA_TOKEN_KEY)',done:Boolean(c.STRAVA_TOKEN_KEY)},{id:'retention',label:'Limpieza automática de la caché comprobada (STRAVA_RETENTION_JOB_ENABLED)',done:c.STRAVA_RETENTION_JOB_ENABLED==='true'},{id:'webhook',label:'Webhook público para sincronizar sin abrir la web (opcional)',done:Boolean(c.STRAVA_WEBHOOK_SUBSCRIPTION_ID&&c.STRAVA_WEBHOOK_PATH_SECRET),optional:true}];
 }
 async begin(user,settings,cookie){if(!this.configured())throw Error('configuration_pending');if(this.config.STRAVA_RETENTION_JOB_ENABLED!=='true')throw Error('retention_pending');const s=cleanSettings(settings),state=randomSecret();await this.q('INSERT INTO strava_oauth (hash,user_id,cookie_hash,expires_at,settings) VALUES (?,?,?,?,?)',await digest(state),user,await digest(cookie),now()+900,JSON.stringify(s)).run();const url=new URL('https://www.strava.com/oauth/authorize');url.search=new URLSearchParams({client_id:this.config.STRAVA_CLIENT_ID,redirect_uri:this.config.STRAVA_REDIRECT_URI,response_type:'code',approval_prompt:'force',scope:s.includePrivate?'read,activity:read,activity:read_all':'read,activity:read',state}).toString();return url.toString();}
 async finish(user,state,cookie,code,callbackScopes){const hash=await digest(state);const row=await this.q('SELECT * FROM strava_oauth WHERE hash=? AND user_id=? AND cookie_hash=? AND expires_at>?',hash,user,await digest(cookie),now()).first();if(!row)throw Error('invalid_oauth_state');const used=await this.q('DELETE FROM strava_oauth WHERE hash=? AND user_id=? RETURNING hash',hash,user).first();if(!used)throw Error('invalid_oauth_state');
 const r=await this.fetcher('https://www.strava.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:this.config.STRAVA_CLIENT_ID,client_secret:this.config.STRAVA_CLIENT_SECRET,code,grant_type:'authorization_code'}),signal:AbortSignal.timeout(8000)});if(!r.ok)throw new ProviderError(r.status);const d=await r.json(),scopes=scopeList(d.scope||callbackScopes);if(!canReadActivities(scopes))throw new ProviderError(403);if(!d.access_token||!d.refresh_token||!d.athlete?.id||!Number.isFinite(d.expires_at))throw new ProviderError(502);
 await this.verify(d.access_token,d.athlete.id);await this.saveConnection(user,String(d.athlete.id),{accessToken:d.access_token,refreshToken:d.refresh_token,expiresAt:d.expires_at},'oauth',scopes);const settings=await this.setSettings(user,JSON.parse(row.settings));await this.sync(user,settings.days);return true;}
 async verify(token,athleteId){await this.budget();const r=await this.fetcher('https://www.strava.com/api/v3/athlete',{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new ProviderError(r.status);const athlete=await r.json();if(!athlete.id||athleteId&&String(athleteId)!==String(athlete.id))throw new ProviderError(403);await this.budget();const activities=await this.fetcher('https://www.strava.com/api/v3/athlete/activities?per_page=1',{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(8000)});if(!activities.ok)throw new ProviderError(activities.status);return athlete;}
 // Not exposed over HTTP: people connect only through OAuth. Kept for server-side fixtures and tests.
 async ownToken(user,token,settings){if(!await this.lock('connect:'+user,30))throw Error('connection_busy');if(!this.config.STRAVA_TOKEN_KEY)throw Error('configuration_pending');if(this.config.STRAVA_RETENTION_JOB_ENABLED!=='true')throw Error('retention_pending');if(typeof token!=='string'||token.length<10||token.length>500||/\s/.test(token))throw Error('invalid_token');const athlete=await this.verify(token);await this.saveConnection(user,String(athlete.id),{accessToken:token,refreshToken:null,expiresAt:null},'token',[]);const s=await this.setSettings(user,settings);await this.sync(user,s.days);}
 async saveConnection(user,athlete,tokens,mode,scopes){const other=await this.q('SELECT user_id FROM strava_connection WHERE athlete_id=? AND user_id<>?',athlete,user).first();if(other)throw Error('athlete_already_linked');const existing=await this.connection(user);if(existing&&existing.athlete_id!==athlete)throw Error('disconnect_first');const version=crypto.randomUUID(),cipher=await seal(tokens,this.config.STRAVA_TOKEN_KEY,user);await this.db.batch([this.q('DELETE FROM strava_jobs WHERE user_id=?',user),this.q('INSERT INTO strava_connection (user_id,athlete_id,cipher,mode,scopes,status,verified_at,last_sync,version) VALUES (?,?,?,?,?,?,?,NULL,?) ON CONFLICT(user_id) DO UPDATE SET athlete_id=excluded.athlete_id,cipher=excluded.cipher,mode=excluded.mode,scopes=excluded.scopes,status=excluded.status,verified_at=excluded.verified_at,version=excluded.version',user,athlete,cipher,mode,JSON.stringify(scopes),'connected',now(),version)]);}
 async access(c){let tokens=await open(c.cipher,this.config.STRAVA_TOKEN_KEY,c.user_id);if(tokens.expiresAt&&tokens.expiresAt<=now()+60){tokens=await rotateTokens(tokens,this.config,this.fetcher);const result=await this.q('UPDATE strava_connection SET cipher=?,verified_at=? WHERE user_id=? AND version=?',await seal(tokens,this.config.STRAVA_TOKEN_KEY,c.user_id),now(),c.user_id,c.version).run();if(!result.meta.changes)throw new ProviderError(401);}return tokens.accessToken;}
 async lock(key,ttl){const t=now();const r=await this.q('INSERT INTO strava_control (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value WHERE strava_control.value<=?',key,t+ttl,t).run();return Boolean(r.meta.changes);}
 async budget(){const t=now();const blocked=await this.q('SELECT value FROM strava_control WHERE key=?','blocked_until').first();if(blocked?.value>t)throw new ProviderError(429,blocked.value);const minute=Math.floor(t/900),date=Math.floor(t/86400);for(const [key,limit,until] of [[`budget:quarter:${minute}`,90,(minute+1)*900],[`budget:day:${date}`,900,(date+1)*86400]]){const r=await this.q('INSERT INTO strava_control (key,value) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET value=value+1 WHERE value<?',key,limit).run();if(!r.meta.changes)throw new ProviderError(429,until);}}
 async api(c,path){await this.budget();const token=await this.access(c);const r=await this.fetcher(`https://www.strava.com/api/v3/${path}`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(8000)});let block=0;for(const prefix of ['x-ratelimit','x-readratelimit']){const limits=(r.headers.get(`${prefix}-limit`)||'').split(',').map(Number),used=(r.headers.get(`${prefix}-usage`)||'').split(',').map(Number);if(limits[0]>0&&used[0]>=limits[0]-2)block=Math.max(block,(Math.floor(now()/900)+1)*900);if(limits[1]>0&&used[1]>=limits[1]-2)block=Math.max(block,(Math.floor(now()/86400)+1)*86400);}if(r.status===429)block=Math.max(block,now()+Number(r.headers.get('retry-after')||900));if(block)await this.q('INSERT INTO strava_control (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=MAX(value,excluded.value)','blocked_until',block).run();if(!r.ok)throw new ProviderError(r.status,block);return r.json();}
 async enqueue(c,kind,payload,id=crypto.randomUUID()){await this.q('INSERT OR IGNORE INTO strava_jobs (id,user_id,version,kind,payload,attempts,due,lease,created) VALUES (?,?,?,?,?,0,?,0,?)',id,c.user_id,c.version,kind,JSON.stringify(payload),now(),now()).run();}
 async sync(user,days){if(this.config.STRAVA_RETENTION_JOB_ENABLED!=='true')throw Error('retention_pending');const c=await this.connection(user);if(!c)throw Error('not_connected');const jobs=await this.q('SELECT id FROM strava_jobs WHERE user_id=? AND attempts<8',user).first();if(jobs)return;await this.q('DELETE FROM strava_jobs WHERE user_id=? AND attempts>=8',user).run();const s=await this.settings(user),start=days?now()-cleanSettings({...s,days}).days*86400:Math.max(now()-s.days*86400,(c.last_sync||0)-2*86400);await this.enqueue(c,'list',{after:start,page:1});const cached=await this.q('SELECT external_id FROM strava_cache WHERE user_id=?',user).all();for(const row of cached.results)await this.enqueue(c,'detail',{externalId:row.external_id},`reconcile:${c.version}:${row.external_id}`);await this.q('UPDATE strava_connection SET status=? WHERE user_id=? AND version=?','syncing',user,c.version).run();}
 async cacheRun(c,raw){const current=await this.connection(c.user_id);if(current?.version!==c.version)return;if(String(raw.athlete?.id||c.athlete_id)!==c.athlete_id)throw new ProviderError(403);const ext=String(raw.id),settings=await this.settings(c.user_id);if(!allowedRun(raw,settings)){await this.q('DELETE FROM strava_cache WHERE user_id=? AND external_id=?',c.user_id,ext).run();return;}const normalized=normalizeRun(raw),existing=await this.q('SELECT id FROM strava_cache WHERE user_id=? AND external_id=?',c.user_id,ext).first();const id=existing?.id||crypto.randomUUID();await this.q('INSERT INTO strava_cache (id,user_id,external_id,data,expires_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM strava_connection WHERE user_id=? AND version=?) ON CONFLICT(user_id,external_id) DO UPDATE SET data=excluded.data,expires_at=excluded.expires_at',id,c.user_id,ext,JSON.stringify(normalized),now()+CACHE_SECONDS,c.user_id,c.version).run();}
 async drain(limit=6){if(!await this.lock('worker',90))return;const started=Date.now();try{await this.purge();for(let i=0;i<limit&&Date.now()-started<18000;i++){const job=await this.q('SELECT * FROM strava_jobs WHERE due<=? AND lease<=? AND attempts<8 ORDER BY created,id LIMIT 1',now(),now()).first();if(!job)break;await this.q('UPDATE strava_jobs SET lease=? WHERE id=?',now()+90,job.id).run();const c=await this.connection(job.user_id);if(!c||c.version!==job.version){await this.q('DELETE FROM strava_jobs WHERE id=?',job.id).run();continue;}try{const payload=JSON.parse(job.payload);
 if(job.kind==='list'){const list=await this.api(c,`athlete/activities?after=${payload.after}&page=${payload.page}&per_page=30`);if(!Array.isArray(list))throw new ProviderError(502);const s=await this.settings(c.user_id);for(const a of list)if(allowedRun(a,s))await this.enqueue(c,'detail',{externalId:String(a.id)},`detail:${c.version}:${a.id}`);if(list.length===30)await this.enqueue(c,'list',{...payload,page:payload.page+1});}
 if(job.kind==='detail'){try{await this.cacheRun(c,await this.api(c,`activities/${encodeURIComponent(payload.externalId)}`));}catch(e){if(e.status===404)await this.q('DELETE FROM strava_cache WHERE user_id=? AND external_id=?',c.user_id,payload.externalId).run();else throw e;}}
 if(job.kind==='revoke'){try{await this.api(c,'athlete');}catch(e){if(e.status===401){await this.disconnect(c.user_id,false);continue;}throw e;}}
 await this.q('DELETE FROM strava_jobs WHERE id=?',job.id).run();const remain=await this.q('SELECT COUNT(*) n FROM strava_jobs WHERE user_id=?',c.user_id).first();await this.q('UPDATE strava_connection SET status=?,last_sync=CASE WHEN ?=0 THEN ? ELSE last_sync END,verified_at=? WHERE user_id=? AND version=?',remain.n?'syncing':'connected',remain.n,now(),now(),c.user_id,c.version).run();
 }catch(e){if(e.status===401||e.status===403)await this.q('DELETE FROM strava_cache WHERE user_id=?',c.user_id).run();const attempts=job.attempts+1,delay=e.retryAt||now()+Math.min(3600,30*2**attempts);await this.q('UPDATE strava_jobs SET attempts=?,due=?,lease=0 WHERE id=?',e.status===401||e.status===403?8:attempts,delay,job.id).run();await this.q('UPDATE strava_connection SET status=? WHERE user_id=? AND version=?',safeError(e),c.user_id,c.version).run();if(e.status===429)break;}}
 }finally{await this.q('DELETE FROM strava_control WHERE key=?','worker').run();}}
 async background(){await this.purge();const rows=await this.q('SELECT * FROM strava_connection WHERE status<>?','authorization_expired').all();for(const c of rows.results)if(!c.last_sync||c.last_sync<now()-86400)await this.sync(c.user_id);await this.drain();}
 async webhook(event){if(String(event.subscription_id)!==String(this.config.STRAVA_WEBHOOK_SUBSCRIPTION_ID))throw Error('invalid_webhook');if(!['activity','athlete'].includes(event.object_type)||!['create','update','delete'].includes(event.aspect_type)||!Number.isSafeInteger(event.object_id)||!Number.isSafeInteger(event.owner_id)||!Number.isSafeInteger(event.event_time)||Math.abs(now()-event.event_time)>86400)throw Error('invalid_webhook');const c=await this.q('SELECT * FROM strava_connection WHERE athlete_id=?',String(event.owner_id)).first();if(!c)return;const kind=event.object_type==='athlete'?'revoke':'detail';// Never trust a forged delete: confirm deletion with an authenticated API request.
 await this.enqueue(c,kind,{externalId:String(event.object_id)},`event:${c.version}:${event.object_type}:${event.object_id}:${event.aspect_type}:${event.event_time}`);}
 async note(user,id,body){const existing=await this.q('SELECT id FROM strava_cache WHERE id=? AND user_id=?',id,user).first()||await this.q('SELECT id FROM strava_notes WHERE id=? AND user_id=?',id,user).first();if(!existing)throw Error('not_found');const check=(v,max)=>v==null||v===''?null:(!Number.isFinite(+v)||+v<1||+v>max?NaN:+v);const rpe=check(body.rpe,10),fatigue=check(body.fatigue,10);if(Number.isNaN(rpe)||Number.isNaN(fatigue)||!['none','mild','relevant'].includes(body.pain||'none'))throw Error('invalid_note');const note={text:String(body.text||'').slice(0,5000),rpe,fatigue,pain:body.pain||'none',feeling:String(body.feeling||'').slice(0,500)};await this.q('INSERT INTO strava_notes (id,user_id,data) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE strava_notes.user_id=excluded.user_id',id,user,JSON.stringify(note)).run();}
 async disconnect(user,revoke=true){const c=await this.connection(user);await this.db.batch([this.q('DELETE FROM strava_jobs WHERE user_id=?',user),this.q('DELETE FROM strava_cache WHERE user_id=?',user),this.q('DELETE FROM strava_oauth WHERE user_id=?',user),this.q('DELETE FROM strava_connection WHERE user_id=?',user)]);let revoked=!c;if(c&&revoke)try{const tokens=await open(c.cipher,this.config.STRAVA_TOKEN_KEY,user);const cfg=this.config;const r=cfg.STRAVA_CLIENT_ID&&cfg.STRAVA_CLIENT_SECRET?await this.fetcher('https://www.strava.com/oauth/revoke',{method:'POST',headers:{Authorization:`Basic ${btoa(`${cfg.STRAVA_CLIENT_ID}:${cfg.STRAVA_CLIENT_SECRET}`)}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:tokens.refreshToken||tokens.accessToken}),signal:AbortSignal.timeout(8000)}):await this.fetcher('https://www.strava.com/oauth/deauthorize',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({access_token:tokens.accessToken}),signal:AbortSignal.timeout(8000)});revoked=r.ok;}catch{}return {disconnected:true,revoked};}
 async erase(user){await this.disconnect(user);await this.db.batch([this.q('DELETE FROM strava_notes WHERE user_id=?',user),this.q('DELETE FROM strava_settings WHERE user_id=?',user)]);}
}
