import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const runnerState = sqliteTable('runner_state', {userId:text('user_id').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull().default(0),updatedAt:text('updated_at').notNull()});
// Every user-owned row is scoped by the authenticated application user ID.
export const stravaConnection=sqliteTable('strava_connection',{userId:text('user_id').primaryKey(),athleteId:text('athlete_id').notNull().unique(),cipher:text('cipher').notNull(),mode:text('mode').notNull(),scopes:text('scopes').notNull(),status:text('status').notNull(),verifiedAt:integer('verified_at').notNull(),lastSync:integer('last_sync'),version:text('version').notNull()});
export const stravaSettings=sqliteTable('strava_settings',{userId:text('user_id').primaryKey(),data:text('data').notNull()});
export const stravaOAuth=sqliteTable('strava_oauth',{hash:text('hash').primaryKey(),userId:text('user_id').notNull(),cookieHash:text('cookie_hash').notNull(),expiresAt:integer('expires_at').notNull(),settings:text('settings').notNull()});
export const stravaCache=sqliteTable('strava_cache',{id:text('id').primaryKey(),userId:text('user_id').notNull(),externalId:text('external_id').notNull(),data:text('data').notNull(),expiresAt:integer('expires_at').notNull()},t=>[uniqueIndex('strava_cache_owner_activity').on(t.userId,t.externalId),index('strava_cache_expiry').on(t.expiresAt)]);
export const stravaNotes=sqliteTable('strava_notes',{id:text('id').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull()});
export const stravaJobs=sqliteTable('strava_jobs',{id:text('id').primaryKey(),userId:text('user_id').notNull(),version:text('version').notNull(),kind:text('kind').notNull(),payload:text('payload').notNull(),attempts:integer('attempts').notNull().default(0),due:integer('due').notNull(),lease:integer('lease').notNull().default(0),created:integer('created').notNull()},t=>[index('strava_jobs_due').on(t.due,t.lease),index('strava_jobs_owner').on(t.userId)]);
export const stravaControl=sqliteTable('strava_control',{key:text('key').primaryKey(),value:integer('value').notNull()});
